### ISSUE TITLE
Heap Profiler can't profile pthread_create since glibc 2.26

### ISSUE THREAD

**Issue by xiaoyur347** [gperftools/gperftools#1010]
We use this environment to do heap profiler.
export HEAP_PROFILE_MMAP=true
It works for ubuntu 16.04 and pthread_create() call mmap() inner.
But in ubuntu 18.04, I find gperftools heap profiler no longer profile pthread_create().
I investigate the problem and find https://github.com/bminor/glibc/commit/fa872e1b6210e81e60d6029429f0a083b8eab26e
From glibc 2.26, pthread_create() call __mmap() for inner use.

So I suggest gperftools add __mmap() hook.

**Comment by alk** [comment]
I am not sure hooking __mmap would work. Not sure why glibc went this way, but since threads are their "guts", they have right to do whatever they want.

Let me CC Adhemerval for his opinion. @zatrazz

**Comment by zatrazz** [comment]
This is an implementation detail: I changed on how libpthread call mmap to avoid a static link namespace issue when using C11 threads (which is unfortunately not in GLIBC yet, but we are getting there). The idea is to avoid pulling 'mmap' symbol and 'poluting' the link namespace (since the user can define its own mmap symbol).

In any case, hooking __mmap should work and one option is to hook on both mmap and __mmap for 
HEAP_PROFILE_MMAP. Keep in mind libc.so exports __mmap in GLIBC_PRIVATE namespace, so it is not a public ABI is thus not subject to stability. However since now mmap is a somewhat complex implementation for some targets (to handle multiple page sizes), I think pthread calls to __mmap won't change anytime soon.

**Comment by alk** [comment]
Ok then. Thanks. I'll gladly accept patch that intercepts __mmap (assuming it works).

**Comment by alk** [comment]
So I am currently spending quite some time in that mmap interception facility as part of issue #1407.

I see that glibc does __map thingy to avoid plt indirection (BTW, why? mmap is never so cheap that plt indirection is expensive. Some "avoid runtime dl.so calls"?)

I.e. even if we define our own __mmap it won't cause glibc to call ours. So I guess closing as won't fix.

There is possibility now via syscall interception facility added originally for wine, but it is 5.11+ and x86 only (see man prctl for PR_SET_SYSCALL_USER_DISPATCH). But this is even more unportable.

We could also go crazy and intercept pthread calls. I think asan folks likely do that. But we cannot afford that much complexity.

Another thing is musl's own __mmap is not even visible. They also do stacks mappings with __mmap.

**Comment by alk** [comment]
BTW I am about to entirely amputate mmap profiling (people can always do their own; feel free to "steal" some of our code if necessary )
