### ISSUE TITLE
Profiling does not happen across fork() calls

### ISSUE THREAD

**Issue by alk** [gperftools/gperftools#107]
Originally reported on Google Code with ID 104

```
What steps will reproduce the problem?
1. Start a program linked with the google perftools libraries.
2. Have the program fork() a child and let the parent process exit.
3. Have the child process profile some piece of code by calling 
ProfilerStart().

What is the expected output? What do you see instead?

The expected output is that profile data should be produced. However, in 
reality, no profiles will be produced. This is because the periodic SIGPROF 
alarm generated by the call to setitimer() is not inherited across fork() 
system calls.

What version of the product are you using? On what operating system?

Version 1.0. Linux 2.6.27.

Please provide any additional information below.

One fix might be to use pthread_atfork() call inside 
CpuProfiler::CpuProfiler() in profiler.cc. The pthread_atfork() can ensure 
that ProfilerRegisterThread() is called immediately upon forking a new 
child process.



```

Reported by `mohit.aron` on 2009-02-05 07:31:25

**Comment by MansiJ1111** [comment]
#include <stdio.h>
#include <sys/types.h>
#include <unistd.h>
void func1(){
	int i=0;
	while(i<100000){
		++i;
	}
}

void func2(){
	int i=0;
	while(i<200000){
		++i;
	}
}

void func3(){
	for(int i=0;i<1000;++i){
		func1();
		func2();

	}
}
int main(int argc, char *argv[])
{
    printf("PID of parent = %d\n", getpid());
    func3();
   int p;
    p = fork();
    if(p==-1)
    {
        printf("There is an error while calling fork()");
    }
    if(p==0)
    {
    printf("We are in the child process\n");
   
    }
    else
    {
        printf("We are in the parent process");
    }
    return 0;
}

I am trying to profile the above program which forks a child process.Currently using gperftool version 2.1.
The program doesnt call exec().
Is this issued solved now because it is mentioned in the document that this issue will be resolved in perftool 1.2?
If yes,what are the steps to profile the child process?
If no,is there any plan to get this issue solved?
