### ISSUE TITLE
Cross Compile Error，Help

### ISSUE THREAD

**Issue by urhue** [gperftools/gperftools#1108]
I Cross Compile Gperftools on Debian Sid with folloing command

> export HOST=x86_64-w64-mingw32
> apt-get update
> apt-get install -y gcc-mingw-w64 g++-mingw-w64  pkg-config autoconf automake autotools-dev autopoint curl wget libtool git gcc g++ gettext make quilt unzip screen libxslt-dev xsltproc docbook-xsl libcppunit-dev curl binutils build-essential bzip2 cpp dh-autoreconf dpkg-dev
> apt-get install -y autoconf autopoint automake gettext libtool pkg-config libcppunit-dev  
> apt-get install libc6-dev libc6-amd64-cross libc6-dev-amd64-cross
> apt-get upgrade -y ca-certificates

> HOST=x86_64-w64-mingw32

> PREFIX=/usr/x86_64-w64-mingw32`

>  mkdir ./tcmalloc && git clone  https://github.com/gperftools/gperftools.git ./tcmalloc
>   cd ./tcmalloc
>   sh autogen.sh
>   CC=$HOST-gcc CXX=$HOST-g++ AR=$HOST-ar RANLIB=$HOST-ranlib ./configure --prefix=$PREFIX --host=$HOST --enable-static 
>   make -j$CPUCOUNT
>   make install -j$CPUCOUNT

But It seemed Error.
```

> src/base/sysinfo.cc: In function ‘void SleepForMilliseconds(int)’:
src/base/sysinfo.cc:247:22: warning: ‘void _sleep(long unsigned int)’ is deprecated [-Wdeprecated-declarations]
   _sleep(milliseconds);   // Windows's _sleep takes milliseconds argument
                      ^
In file included from /usr/lib/gcc/x86_64-w64-mingw32/8.3-win32/include/c++/cstdlib:75,
                 from /usr/lib/gcc/x86_64-w64-mingw32/8.3-win32/include/c++/stdlib.h:36,
                 from /usr/lib/gcc/x86_64-w64-mingw32/8.3-win32/include/mm_malloc.h:27,
                 from /usr/lib/gcc/x86_64-w64-mingw32/8.3-win32/include/xmmintrin.h:34,
                 from /usr/lib/gcc/x86_64-w64-mingw32/8.3-win32/include/x86intrin.h:33,
                 from /usr/share/mingw-w64/include/winnt.h:1554,
                 from /usr/share/mingw-w64/include/minwindef.h:163,
                 from /usr/share/mingw-w64/include/windef.h:8,
                 from /usr/share/mingw-w64/include/windows.h:69,
                 from ./src/windows/port.h:56,
                 from ./src/windows/mingw.h:70,
                 from ./src/config.h:313,
                 from src/base/sysinfo.cc:31:
/usr/share/mingw-w64/include/stdlib.h:659:24: note: declared here
   _CRTIMP void __cdecl _sleep(unsigned long _Duration) __MINGW_ATTRIB_DEPRECATED;
                        ^~~~~~
src/base/sysinfo.cc:247:22: warning: ‘void _sleep(long unsigned int)’ is deprecated [-Wdeprecated-declarations]
   _sleep(milliseconds);   // Windows's _sleep takes milliseconds argument
                      ^
In file included from /usr/lib/gcc/x86_64-w64-mingw32/8.3-win32/include/c++/cstdlib:75,
                 from /usr/lib/gcc/x86_64-w64-mingw32/8.3-win32/include/c++/stdlib.h:36,
                 from /usr/lib/gcc/x86_64-w64-mingw32/8.3-win32/include/mm_malloc.h:27,
                 from /usr/lib/gcc/x86_64-w64-mingw32/8.3-win32/include/xmmintrin.h:34,
                 from /usr/lib/gcc/x86_64-w64-mingw32/8.3-win32/include/x86intrin.h:33,
                 from /usr/share/mingw-w64/include/winnt.h:1554,
                 from /usr/share/mingw-w64/include/minwindef.h:163,
                 from /usr/share/mingw-w64/include/windef.h:8,
                 from /usr/share/mingw-w64/include/windows.h:69,
                 from ./src/windows/port.h:56,
                 from ./src/windows/mingw.h:70,
                 from ./src/config.h:313,
                 from src/base/sysinfo.cc:31:
/usr/share/mingw-w64/include/stdlib.h:659:24: note: declared here
   _CRTIMP void __cdecl _sleep(unsigned long _Duration) __MINGW_ATTRIB_DEPRECATED;
                        ^~~~~~
depbase=`echo src/base/logging.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ./libtool  --tag=CXX   --mode=compile x86_64-w64-mingw32-g++ -std=gnu++11 -DHAVE_CONFIG_H -I. -I./src  -I./src -DNO_TCMALLOC_SAMPLES  -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -fno-builtin-malloc -fno-builtin-free -fno-builtin-realloc -fno-builtin-calloc -fno-builtin-cfree -fno-builtin-memalign -fno-builtin-posix_memalign -fno-builtin-valloc -fno-builtin-pvalloc  -Wno-unused-result -fsized-deallocation -faligned-new  -DNO_FRAME_POINTER -g -O2 -MT src/base/logging.lo -MD -MP -MF $depbase.Tpo -c -o src/base/logging.lo src/base/logging.cc &&\
mv -f $depbase.Tpo $depbase.Plo
src/base/sysinfo.cc: At global scope:
src/base/sysinfo.cc:424:13: warning: ‘bool ParseProcMapsLine(char*, uint64*, uint64*, char*, uint64*, int*, int*, int64*, unsigned int*)’ defined but not used [-Wunused-function]
 static bool ParseProcMapsLine(char *text, uint64 *start, uint64 *end,
             ^~~~~~~~~~~~~~~~~
src/base/sysinfo.cc:401:14: warning: ‘char* CopyStringUntilChar(char*, unsigned int, int, char*)’ defined but not used [-Wunused-function]
 static char *CopyStringUntilChar(
              ^~~~~~~~~~~~~~~~~~~
src/base/sysinfo.cc:373:8: warning: ‘T StringToInteger(char*, char**, int) [with T = long long unsigned int]’ defined but not used [-Wunused-function]
 uint64 StringToInteger<uint64>(char *text, char **endptr, int base) {
        ^~~~~~~~~~~~~~~~~~~~~~~
src/base/sysinfo.cc:368:7: warning: ‘T StringToInteger(char*, char**, int) [with T = long long int]’ defined but not used [-Wunused-function]
 int64 StringToInteger<int64>(char *text, char **endptr, int base) {
       ^~~~~~~~~~~~~~~~~~~~~~
src/base/sysinfo.cc:363:5: warning: ‘T StringToInteger(char*, char**, int) [with T = int]’ defined but not used [-Wunused-function]
 int StringToInteger<int>(char *text, char **endptr, int base) {
     ^~~~~~~~~~~~~~~~~~~~
libtool: compile:  x86_64-w64-mingw32-g++ -std=gnu++11 -DHAVE_CONFIG_H -I. -I./src -I./src -DNO_TCMALLOC_SAMPLES -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -fno-builtin-malloc -fno-builtin-free -fno-builtin-realloc -fno-builtin-calloc -fno-builtin-cfree -fno-builtin-memalign -fno-builtin-posix_memalign -fno-builtin-valloc -fno-builtin-pvalloc -Wno-unused-result -fsized-deallocation -faligned-new -DNO_FRAME_POINTER -g -O2 -MT src/base/logging.lo -MD -MP -MF src/base/.deps/logging.Tpo -c src/base/logging.cc  -DDLL_EXPORT -DPIC -o src/base/.libs/logging.o
libtool: compile:  x86_64-w64-mingw32-g++ -std=gnu++11 -DHAVE_CONFIG_H -I. -I./src -I./src -DNO_TCMALLOC_SAMPLES -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -fno-builtin-malloc -fno-builtin-free -fno-builtin-realloc -fno-builtin-calloc -fno-builtin-cfree -fno-builtin-memalign -fno-builtin-posix_memalign -fno-builtin-valloc -fno-builtin-pvalloc -Wno-unused-result -fsized-deallocation -faligned-new -DNO_FRAME_POINTER -g -O2 -MT src/base/sysinfo.lo -MD -MP -MF src/base/.deps/sysinfo.Tpo -c src/base/sysinfo.cc -o src/base/sysinfo.o >/dev/null 2>&1
depbase=`echo src/base/dynamic_annotations.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ./libtool  --tag=CC   --mode=compile x86_64-w64-mingw32-gcc -DHAVE_CONFIG_H -I. -I./src  -I./src -DNO_TCMALLOC_SAMPLES   -g -O2 -MT src/base/dynamic_annotations.lo -MD -MP -MF $depbase.Tpo -c -o src/base/dynamic_annotations.lo src/base/dynamic_annotations.c &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  x86_64-w64-mingw32-gcc -DHAVE_CONFIG_H -I. -I./src -I./src -DNO_TCMALLOC_SAMPLES -g -O2 -MT src/base/dynamic_annotations.lo -MD -MP -MF src/base/.deps/dynamic_annotations.Tpo -c src/base/dynamic_annotations.c  -DDLL_EXPORT -DPIC -o src/base/.libs/dynamic_annotations.o
/bin/bash ./libtool  --tag=CXX   --mode=link x86_64-w64-mingw32-g++ -std=gnu++11 -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -fno-builtin-malloc -fno-builtin-free -fno-builtin-realloc -fno-builtin-calloc -fno-builtin-cfree -fno-builtin-memalign -fno-builtin-posix_memalign -fno-builtin-valloc -fno-builtin-pvalloc  -Wno-unused-result -fsized-deallocation -faligned-new  -DNO_FRAME_POINTER -g -O2 -no-undefined   -o libmaybe_threads.la     
libtool: link: x86_64-w64-mingw32-ar cru .libs/libmaybe_threads.a 
x86_64-w64-mingw32-ar: `u' modifier ignored since `D' is the default (see `U')
libtool: link: x86_64-w64-mingw32-ranlib .libs/libmaybe_threads.a
libtool: link: ( cd ".libs" && rm -f "libmaybe_threads.la" && ln -s "../libmaybe_threads.la" "libmaybe_threads.la" )
depbase=`echo src/tests/atomicops_unittest.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
x86_64-w64-mingw32-g++ -std=gnu++11 -DHAVE_CONFIG_H -I. -I./src  -I./src -DNO_TCMALLOC_SAMPLES  -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -fno-builtin-malloc -fno-builtin-free -fno-builtin-realloc -fno-builtin-calloc -fno-builtin-cfree -fno-builtin-memalign -fno-builtin-posix_memalign -fno-builtin-valloc -fno-builtin-pvalloc  -Wno-unused-result -fsized-deallocation -faligned-new  -DNO_FRAME_POINTER -g -O2 -MT src/tests/atomicops_unittest.o -MD -MP -MF $depbase.Tpo -c -o src/tests/atomicops_unittest.o src/tests/atomicops_unittest.cc &&\
mv -f $depbase.Tpo $depbase.Po
In file included from ./src/windows/mingw.h:70,
                 from ./src/config.h:313,
                 from src/base/dynamic_annotations.c:38:
./src/windows/port.h:419:24: warning: ‘struct pollfd’ declared inside parameter list will not be visible outside of this definition or declaration
 inline int poll(struct pollfd* fds, int nfds, int timeout) {
                        ^~~~~~
In file included from src/base/dynamic_annotations.c:50:
./src/third_party/valgrind.h: In function ‘VALGRIND_PRINTF’:
./src/third_party/valgrind.h:3681:31: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
                               (unsigned long)format, (unsigned long)vargs,
                               ^
./src/third_party/valgrind.h:249:45: note: in definition of macro ‘VALGRIND_DO_CLIENT_REQUEST’
     _zzq_args[1] = (unsigned long long int)(_zzq_arg1);           \
                                             ^~~~~~~~~
./src/third_party/valgrind.h:3681:54: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
                               (unsigned long)format, (unsigned long)vargs,
                                                      ^
./src/third_party/valgrind.h:250:45: note: in definition of macro ‘VALGRIND_DO_CLIENT_REQUEST’
     _zzq_args[2] = (unsigned long long int)(_zzq_arg2);           \
                                             ^~~~~~~~~
./src/third_party/valgrind.h: In function ‘VALGRIND_PRINTF_BACKTRACE’:
./src/third_party/valgrind.h:3696:31: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
                               (unsigned long)format, (unsigned long)vargs,
                               ^
./src/third_party/valgrind.h:249:45: note: in definition of macro ‘VALGRIND_DO_CLIENT_REQUEST’
     _zzq_args[1] = (unsigned long long int)(_zzq_arg1);           \
                                             ^~~~~~~~~
./src/third_party/valgrind.h:3696:54: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
                               (unsigned long)format, (unsigned long)vargs,
                                                      ^
./src/third_party/valgrind.h:250:45: note: in definition of macro ‘VALGRIND_DO_CLIENT_REQUEST’
     _zzq_args[2] = (unsigned long long int)(_zzq_arg2);           \
                                             ^~~~~~~~~
libtool: compile:  x86_64-w64-mingw32-g++ -std=gnu++11 -DHAVE_CONFIG_H -I. -I./src -I./src -DNO_TCMALLOC_SAMPLES -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -fno-builtin-malloc -fno-builtin-free -fno-builtin-realloc -fno-builtin-calloc -fno-builtin-cfree -fno-builtin-memalign -fno-builtin-posix_memalign -fno-builtin-valloc -fno-builtin-pvalloc -Wno-unused-result -fsized-deallocation -faligned-new -DNO_FRAME_POINTER -g -O2 -MT src/base/logging.lo -MD -MP -MF src/base/.deps/logging.Tpo -c src/base/logging.cc -o src/base/logging.o >/dev/null 2>&1
libtool: compile:  x86_64-w64-mingw32-gcc -DHAVE_CONFIG_H -I. -I./src -I./src -DNO_TCMALLOC_SAMPLES -g -O2 -MT src/base/dynamic_annotations.lo -MD -MP -MF src/base/.deps/dynamic_annotations.Tpo -c src/base/dynamic_annotations.c -o src/base/dynamic_annotations.o >/dev/null 2>&1
x86_64-w64-mingw32-g++ -std=gnu++11 -DHAVE_CONFIG_H -I. -I./src  -I./src -DNO_TCMALLOC_SAMPLES  -pthread -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -fno-builtin-malloc -fno-builtin-free -fno-builtin-realloc -fno-builtin-calloc -fno-builtin-cfree -fno-builtin-memalign -fno-builtin-posix_memalign -fno-builtin-valloc -fno-builtin-pvalloc  -Wno-unused-result -fsized-deallocation -faligned-new  -DNO_FRAME_POINTER -fno-builtin -g -O2 -MT src/tests/tcmalloc_minimal_unittest-tcmalloc_unittest.o -MD -MP -MF src/tests/.deps/tcmalloc_minimal_unittest-tcmalloc_unittest.Tpo -c -o src/tests/tcmalloc_minimal_unittest-tcmalloc_unittest.o `test -f 'src/tests/tcmalloc_unittest.cc' || echo './'`src/tests/tcmalloc_unittest.cc
src/tests/tcmalloc_unittest.cc:80:10: fatal error: sys/mman.h: No such file or directory
 #include <sys/mman.h>      // for testing mmap hooks
          ^~~~~~~~~~~~
compilation terminated.
```
 
Can anyone help me ?

**Comment by alk** [comment]
thanks for reporting it. If you just checkout current HEAD^ (or gperftools-2.7-41-gfba6ce0) it'll compile. I'll fix the issue.

**Comment by urhue** [comment]
Dear 

If the 2.7 edition in release page was adopted, it is ok. 
And I have a confusion ,in release page,the edition is a little old...

Thanks

**Comment by urhue** [comment]
> 
> 
> thanks for reporting it. If you just checkout current HEAD^ (or gperftools-2.7-41-gfba6ce0) it'll compile. I'll fix the issue.

Dear

If the 2.7 edition in release page was adopted, it is ok.
And I have a confusion ,in release page,the edition is a little old...

Thanks

**Comment by urhue** [comment]
> 
> 
> thanks for reporting it. If you just checkout current HEAD^ (or gperftools-2.7-41-gfba6ce0) it'll compile. I'll fix the issue.

Seemed still illed

`x86_64-w64-mingw32-g++ -std=gnu++11 -DHAVE_CONFIG_H -I. -I./src  -I./src -DNO_TCMALLOC_SAMPLES  -DNO_TCMALLOC_SAMPLES -DNO_HEAP_CHECK -pthread -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -fno-builtin-malloc -fno-builtin-free -fno-builtin-realloc -fno-builtin-calloc -fno-builtin-cfree -fno-builtin-memalign -fno-builtin-posix_memalign -fno-builtin-valloc -fno-builtin-pvalloc  -Wno-unused-result -fsized-deallocation   -DNO_FRAME_POINTER -fno-builtin -g -O2 -MT src/tcm_min_asserts_unittest-malloc_hook.o -MD -MP -MF src/.deps/tcm_min_asserts_unittest-malloc_hook.Tpo -c -o src/tcm_min_asserts_unittest-malloc_hook.o `test -f 'src/malloc_hook.cc' || echo './'`src/malloc_hook.cc
src/symbolize.cc:84:20: warning: ‘const char* GetProgramInvocationName()’ defined but not used [-Wunused-function]
 static const char* GetProgramInvocationName() {
                    ^~~~~~~~~~~~~~~~~~~~~~~~
src/symbolize.cc:73:14: warning: ‘char* get_pprof_path()’ defined but not used [-Wunused-function]
 static char* get_pprof_path() {
              ^~~~~~~~~~~~~~
src/malloc_hook.cc:41:23: fatal error: sys/mman.h: No such file or directory
 # include <sys/mman.h>
                       ^
compilation terminated.`

**Comment by SKIYET** [comment]
> 
> 
> thanks for reporting it. If you just checkout current HEAD^ (or gperftools-2.7-41-gfba6ce0) it'll compile. I'll fix the issue.

Dear

I am sorry for boring you but
Anything done?

Thanks

**Comment by lifof** [comment]
Hello there
just in case someone is still having problems with this #include <sys/mman.h>.

1. get the lib port from here : https://code.google.com/archive/p/mman-win32/
2. compile it and install it using good old : `./configure && make && make install` under msys2 it will be installed by default on the /mingw folder so depending on your build system copy and paste the include & lib folders in /mingw to /mingw64 or /mingw32 now that mman lib port is installed you can proceed to building gperftools.
3. now using in the gperftools folder `./configure && make` you're still going to have a link error so open `libwindows.la` and replace the line with `dependency_libs=' -lpsapi'`  >> `dependency_libs=' -lpsapi -lmman'`
4. `make && make install` once again

and you're done.

Have a great day

**Comment by SKIYET** [comment]
> 
> 
> Hello there
> just in case someone is still having problems with this #include <sys/mman.h>.
> 
>     1. get the lib port from here : https://code.google.com/archive/p/mman-win32/
> 
>     2. compile it and install it using good old : `./configure && make && make install` under msys2 it will be installed by default on the /mingw folder so depending on your build system copy and paste the include & lib folders in /mingw to /mingw64 or /mingw32 now that mman lib port is installed you can proceed to building gperftools.
> 
>     3. now using in the gperftools folder `./configure && make` you're still going to have a link error so open `libwindows.la` and replace the line with `dependency_libs=' -lpsapi'`  >> `dependency_libs=' -lpsapi -lmman'`
> 
>     4. `make && make install` once again
> 
> 
> and you're done.
> 
> Have a great day

Dear

I tested debian sid and ubuntu 19.04.
If I use apt to install mingw-w64 and tools.
This issue will appear.
Not what you said "only some case".

Why the gperftools-2.7-41-gfba6ce0 is ok but the newest source is illed?

Thanks

**Comment by SKIYET** [comment]
The compile passed after install mman.
And is there a performance loss?

Thanks

**Comment by SKIYET** [comment]
I tested your 2.7.9.
This problem is still in this release.
OS: Debian 10 stable/sid
whether posix or not, the program still tell me " fatal error: sys/mman.h: No such file or directory"

@alk 

Some plan to this issue?

x86_64-w64-mingw32-g++-posix -std=gnu++11 -DHAVE_CONFIG_H -I. -I./src  -I./src -DNO_TCMALLOC_SA                                                                                                                           MPLES   -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -fno-builtin-malloc -fno-b                                                                                                                           uiltin-free -fno-builtin-realloc -fno-builtin-calloc -fno-builtin-cfree -fno-builtin-memalign -                                                                                                                           fno-builtin-posix_memalign -fno-builtin-valloc -fno-builtin-pvalloc  -Wno-unused-result -fsized                                                                                                                           -deallocation -faligned-new  -DNO_FRAME_POINTER -fno-builtin -g -O2 -MT src/tests/tcmalloc_mini                                                                                                                           mal_unittest-testutil.o -MD -MP -MF src/tests/.deps/tcmalloc_minimal_unittest-testutil.Tpo -c -                                                                                                                           o src/tests/tcmalloc_minimal_unittest-testutil.o `test -f 'src/tests/testutil.cc' || echo './'`                                                                                                                           src/tests/testutil.cc
src/maybe_threads.cc:62:7: warning: ‘int pthread_key_create(pthread_key_t*, void (*)(void*))’ r                                                                                                                           edeclared without dllimport attribute after being referenced with dll linkage
   int pthread_key_create (pthread_key_t*, void (*)(void*))
       ^~~~~~~~~~~~~~~~~~
src/maybe_threads.cc:64:7: warning: ‘int pthread_key_delete(pthread_key_t)’ redeclared without                                                                                                                            dllimport attribute after being referenced with dll linkage
   int pthread_key_delete (pthread_key_t)
       ^~~~~~~~~~~~~~~~~~
src/maybe_threads.cc:66:9: warning: ‘void* pthread_getspecific(pthread_key_t)’ redeclared witho                                                                                                                           ut dllimport attribute after being referenced with dll linkage
   void *pthread_getspecific(pthread_key_t)
         ^~~~~~~~~~~~~~~~~~~
src/maybe_threads.cc:68:7: warning: ‘int pthread_setspecific(pthread_key_t, const void*)’ redec                                                                                                                           lared without dllimport attribute after being referenced with dll linkage
   int pthread_setspecific(pthread_key_t, const void*)
       ^~~~~~~~~~~~~~~~~~~
src/maybe_threads.cc:70:7: warning: ‘int pthread_once(pthread_once_t*, void (*)())’ redeclared                                                                                                                            without dllimport attribute after being referenced with dll linkage
   int pthread_once(pthread_once_t *, void (*)(void))
       ^~~~~~~~~~~~
src/tests/tcmalloc_unittest.cc:80:10: fatal error: sys/mman.h: No such file or directory
 #include <sys/mman.h>      // for testing mmap hooks
          ^~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:6137: src/tests/tcmalloc_minimal_unittest-tcmalloc_unittest.o] Error 1
make: *** Waiting for unfinished jobs....
libtool: compile:  x86_64-w64-mingw32-g++-posix -std=gnu++11 -DHAVE_CONFIG_H -I. -I./src -I./sr                                                                                                                           c -DNO_TCMALLOC_SAMPLES -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -fno-built                                                                                                                           in-malloc -fno-builtin-free -fno-builtin-realloc -fno-builtin-calloc -fno-builtin-cfree -fno-bu                                                                                                                           iltin-memalign -fno-builtin-posix_memalign -fno-builtin-valloc -fno-builtin-pvalloc -Wno-unused                                                                                                                           -result -fsized-deallocation -faligned-new -DNO_FRAME_POINTER -g -O2 -MT src/maybe_threads.lo -                                                                                                                           MD -MP -MF src/.deps/maybe_threads.Tpo -c src/maybe_threads.cc -o src/maybe_threads.o >/dev/nul                                                                                                                           l 2>&1
mv -f src/tests/.deps/tcmalloc_minimal_unittest-testutil.Tpo src/tests/.deps/tcmalloc_minimal_u                                                                                                                           nittest-testutil.Po

**Comment by alk** [comment]
Thanks for ping. I'll look on weekend.

**Comment by alk** [comment]
Should be fixed. Apologies for somehow missing this problem.
