### ISSUE TITLE
tcmalloc: pthread_atfork and dynamic linking

### ISSUE THREAD

**Issue by smirnov-vs** [gperftools/gperftools#1110]
Hello.

I have an application using tcmalloc and fork.
I experienced random deadlocks after forking and after some investigating it turned out that `pthread_atfork` is `nullptr`.
Production OS is CentOS 6 or 7.
Then I tested it on my laptop with Ubuntu 18.04 Linux 5.1 and result was non-null. Dynamic linking on my computer works.
LD_PRELOAD doesn't have any effect on CentOS.
pthread is linked after libtcmalloc.a

I've made some code to show this result.

In `maybe_threads.cc` I added `fprintf` to get value of function pointer 
```
  fprintf(stderr, "POINTER: %p\n", pthread_atfork);
  if (pthread_atfork) {
    int rv = pthread_atfork(before, parent_after, child_after);
    CHECK(rv == 0);
  }
```

Then I wrote simple CMake project:
```
cmake_minimum_required(VERSION 2.8)
project(tcmalloc_weak)

link_libraries(***PATH TO libtcmalloc.a*** pthread)
add_executable(tcmalloc_weak main.cpp)
```
and main.cpp:
```
#include <unistd.h>
#include <thread>

int main()
{
	std::thread([] { while (true); }).detach();
	return 0;
}
```

If I run this binary on my laptop result is something like that:
```
POINTER: 0x7f1c18dcd8f0
```
If I run on CentOS:
```
POINTER: (nil)
```

Tests were on Ubuntu laptop and in centos 6 and 7 docker containers on the same laptop.
GCC-8

Solution is to remove weak attribute from pthread_atfork and link tcmalloc with pthread.
But I don't want to live forever with patched tcmalloc library, maybe you can help me find better solution?
I don't know why function is not linked on CentOS.

**Comment by smirnov-vs** [comment]
It turned out that there were no any `pthread_atfork` symbols at executable.
I found that order of symbols in `libtcmalloc.a` in `maybe_thread.cc` is different on Ubuntu and CentOS, then I decided to add `--with-fpic` on configuration gpreftools.
It solved my problem and symbols were added to executable.
A couple days of testing new binary will show if deadlocks are gone.

**Comment by brenoguim** [comment]
@smirnov-vs , are you running on ARM? I can see this issue too, but only on ARM.

It seems that `pthread_atfork` does not exist on `libpthread.so.0` but instead it's present in  `/usr/lib64/libpthread_nonshared.a` which is implicitly linked in when you add `-lpthread` because `/usr/lib64/libpthread.so` is a linker script.

The implementation of `pthread_atfork` just calls `__register_atfork` as far as I can tell.
So the trick of marking the declaration as weak and relying on dynamic linking won't work for this case.

**Comment by alk** [comment]
aha, thanks. Very interesting. Also unsure what is going on. On my very up-to-date debian sid I do get:

```
user@big:~/src/External/gperftools# objdump -T /lib/x86_64-linux-gnu/libc.so.6 | grep atfork
0000000000090b50 g    DF .text	000000000000000c (GLIBC_2.2.5) pthread_atfork
00000000000d39b0 g    DF .text	00000000000001bd  GLIBC_2.3.2 __register_atfork
```

But also yes nonshared thingy too:

```
root@big:~# objdump -t /usr/lib/x86_64-linux-gnu/libc_nonshared.a | grep atfork
pthread_atfork.oS:     file format elf64-x86-64
0000000000000000 g     F .text	000000000000000c .hidden __pthread_atfork
0000000000000000         *UND*	0000000000000000 __register_atfork
0000000000000000  w    F .text	000000000000000c .hidden pthread_atfork
```

Hm, I guess worth checking what other mallocs do. Ours might be one of few that tries to avoid libpthread dependency (this is because some libraries, most notably c++ bits, occasionally enable more expensive codes when threading is activated (and btw they're likely spending more on overheads than actual stuff like atomics but well...))

I.e. it is not huge deal, but I would like us to find way to keep optional-ness of pthread dependency.

**Comment by alk** [comment]
Aha. Indeed glibc does the static library thing so that atfork can also silently pass DSO handle. So that when library is unloaded, it's atfork handlers get dropped as well.

As for pthread dependency being optional, yes, worth dropping that.

Original idea for that is that some libraries tweak their behavior if threading is active or not. And that could/does affect performance. Way way back, libc was one of these. This days libstdc++ has some bits that depend on threadiness. Most notable is shared_ptr bits which do refcounting non-atomically in single threaded programs (but code bloat is imo worse). clang's c++ library doesn't do that runtime code bloat thingy and they're right.

However:

a) glibc (but not musl) already has sys/single_threaded.h with __libc_single_threaded variable and stdc+++ check this. It becomes true after threads are actually created as opposed to -lpthread linked in. And this days libc's libpthread is empty anyways. So us pulling -lpthread as dependency won't affect libstdc++

b) on musl pthread symbols are always available and my understanding is libstdc++ will always behave as if threading is active (bit still have code bloat I think). Same appears to be the case for osex, but they do clang's libc++ anyways.

c) various BSDs and perhaps solaris could benefit from us not pulling -lpthread, but we already do somehow. I checked that libtcmalloc already depends on threading library

So, yes, time to simplify everything and just do threads all the time
