### ISSUE TITLE
link with tcmalloc program stop every five minute

### ISSUE THREAD

**Issue by wangjinnana** [gperftools/gperftools#1149]
I use gperftools to profile heap my program
tcmalloc version libtcmalloc.so.4.1.0,
my command is:
PPROF_PATH=/usr/bin/pprof HEAPCHECK=normal HEAPPROFILE=${FILEPATH}/leak.log ${FILENAME} >> ${FILEPATH}/gperftools.log 2>&1&

I have a monitor program to restart my program every time it down, then i found, the ${FILENAME} restart every five minute, when I just execute my program with command ${FILENAME}, i found it restart every five minute the same.

if some one encounter this problem

**Comment by wangjinnana** [comment]
In my main function, 
HeapProfilerStart("query_server_heap_profile");
// this is my code
HeapProfilerStop();

is something wrong

**Comment by boyxiaolong** [comment]
HEAPCHECK=normal can't use HeapProfilerStart at the sametime

**Comment by alk** [comment]
Hi. Indeed using two ways to start heap checker is not good idea. But also note that heap checker is not intended for production code, it is just for one off checks, such as in unit tests. It does make program run much slower and use more memory so various problems are possible due to that.

Closing, but reopen if you have something to add.
