### ISSUE TITLE
gperftools cpu profiler coroutine process cause segmentation fault

### ISSUE THREAD

**Issue by lkkey80** [gperftools/gperftools#1163]
gperftools cpu profiler coroutine process cause segmentation fault, does cpu profiler conflict with  coroutine implemented with  assembly instruction?

**Comment by alk** [comment]
Not sure about "conflict". Thing is in order to profile we capture stack traces from signal handler. We have 2 ways:

a) using frame pointer register 

b) using libunwind (which uses dwarf-like CFI data that was originally introduced to handle exceptions).

In (b) case your asm needs to have correct CFI annotation so that stack trace capturing works. Easiest way to test is single-step your asm in gdb and try 'bt' on each step and ensure you still have good one.

Coroutine-wise I actually have code with right CFI stuff here: https://github.com/alk/swapcontext_light/blob/master/swapcontext_light.S


In (a) case your asm needs to ensure that frame pointer register (i.e. rbp on x86-64) is correct at any instruction.

Alternative is blocking SIGPROF during switch. So that profiler will not try to "unwind" when cpu is inside your code.

Closing the "ticket" for now. Feel free to reopen if you think there is anything to fix in gperftools.
