### ISSUE TITLE
Paper on latest version of TCMalloc

### ISSUE THREAD

**Issue by karanchahal** [gperftools/gperftools#1176]
Is there any paper that documents the latest changes to tcmalloc since the blog post ? I am writing a survey and would be grateful if I can read a paper instead of digging into code.

Thank you,
Karanbir Chahal

**Comment by alk** [comment]
There are not that many changes since original paper was written. And as far as I know no paper describing modern gperftools exists. There is reasonably detailed description of internals of "abseil" tcmalloc fork at: https://github.com/google/tcmalloc/blob/master/docs/design.md. gperftools has many details the same as abseil tcmalloc. Notable differences are lack of huge pages aware page heap allocator (I don't think what they have is ready yet), lack of per-cpu and simpler singly-linked list for central free list.
