### ISSUE TITLE
windoc   crash

### ISSUE THREAD

**Issue by lcldragon** [gperftools/gperftools#1197]
call MallocExtension::instance()->SetNumericProperty("tcmalloc.aggressive_memory_decommit", 			1);
![image](https://user-images.githubusercontent.com/66099447/83212325-e276fc80-a191-11ea-901f-5f07f62ceb6d.png)

**Comment by alk** [comment]
I cannot do anything with this bug report. Usually when people report bugs like that "my program XYZ crashes inside tcmalloc" it is actually memory management bug in the program. I'd need much more specific evidence that problem is indeed tcmalloc.

Closing but feel free to reopen if you have anything to add.
