### ISSUE TITLE
a way to avoid null pointer dereference at no Debug build

### ISSUE THREAD

**Issue by kashirin-alex** [gperftools/gperftools#1302]
_The noticeable build warning at LTO (while tcmalloc is built with `-flto -fuse-linker-plugin -ffat-lto-objects` and `-O3` in this case):_
```CPP
/root/s/gperftools/src/central_freelist.cc: In member function ‘ReleaseToSpans’:
/root/s/gperftools/src/central_freelist.cc:110:13: warning: potential null pointer dereference [-Wnull-dereference]
  110 |   if (span->objects == NULL) {
```

* That is only a way to avoid a segmentation (suppose nullptr has happen at no-debug) and to observe the warning: potential null pointer dereference -- It does not resolve a case when or why the object is out of pages map. 

as the object is for release, as like the behavior of return on nullptr at `void CentralFreeList::ReleaseListToSpans(void* start)` https://github.com/gperftools/gperftools/blob/c25941200ef4ce39d0774c1332ff7abfbeab7035/src/central_freelist.cc#L83 

The `void CentralFreeList::ReleaseToSpans(void* object)` https://github.com/gperftools/gperftools/blob/c25941200ef4ce39d0774c1332ff7abfbeab7035/src/central_freelist.cc#L104
can return on `span` is nullptr as the `Static::pageheap()->GetDescriptor(p);` is nullptr when nothing to release (out-of-range)
https://github.com/gperftools/gperftools/blob/f7c6fb6c8e99d6b1b725e5994373bcd19ffdf8fd/src/pagemap.h#L146

> A finding, the `Span* MapObjectToSpan(void* object)` for not GCC-4.5.0 can be considered for `inline ATTRIBUTE_ALWAYS_INLINE`  (competes the call-graph inlinement instructions)

**Comment by kashirin-alex** [comment]
Further more, the `Span* span` evaluation  
 https://github.com/gperftools/gperftools/blob/c25941200ef4ce39d0774c1332ff7abfbeab7035/src/central_freelist.cc#L105
should/can be before `SLL_Next` by that guarantees Range is good. (and will have a loop-exit in case the Span is a out-of-range/bad address)

-- Are the facts on the Issue good enough for a pull-request ? (just pre-checking)

**Comment by alk** [comment]
Apologies for delay. So you got me confused here. This appears to be unrelated to -flto or -O3. It is caused by -Wnull-dereference which appears to be fairly aggressive and arguably somewhat bogus. Likely, compiler gets confused by layers of "type puning" that inevitably happens in freelists.

In practice objects get to freelist after being tested against sizemap. Well, there is a chance that sized delete will lie to us about object's size and then cause trouble with missing span. But sized delete's future appears to be murky. We don't enable it by default, and apparently nearly everyone too (google runs with it; others probably not).

In any case, testing for null span that late is nearly useless. We cannot continue anyway, so crashing with nullptr reference or explicit assertion failure doesn't buy as much.
