### ISSUE TITLE
Static version of libtcmalloc_minimal crashes in Linux

### ISSUE THREAD

**Issue by alvaropalmaaste** [gperftools/gperftools#1317]
Environment:

* `CentOS Linux release 7.9.2009`
* `gcc 10.2.1`
* `GPerftools 2.9.1`

Same binary, linked against libtcmalloc_minimal static (.a) and dynamic (.so) versions (simply by changing the CMake config file:

- **Dynamic**:  `find_library(GPERF_MEM tcmalloc_minimal)` (CMake always favor dynamic libraries over static)

- **Static**: `find_library(GPERF_MEM libtcmalloc_minimal.a)`

1. Dynamically linked works fine (`ldd` shows `libtcmalloc_minimal.so` in the list of dependencies)
2. Statically linked (confirmed no `libtcmalloc_minimal.so` in the list of dependencies) crashes with:
`src/tcmalloc.cc:333] Attempt to free invalid pointer 0x4db0eb0`

I tried adding `-Wl,--eh-frame-hdr` to the linker, same (bad) result.

I'm interested in the static library since I'd like to deploy my own binary with the smallest amount of extra libraries as possible. And I'm REALLY interested on using TCMalloc, since early tests using the dynamic library shows a 30% boost in performance in the application!!!

Thanks in advance.

**Comment by alk** [comment]
Thanks for bug report. This is really odd. I will need more details about what gets linked. Ideally full way for me to reproduce. But if not that, then perhaps exact command line used that pulls tcmalloc (link order or flags may matter).

tcmalloc is linked into main binary right? (not some .so that gets linked to main binary)

The oddest part is, it should not be possible at all. Looks like something was allocated by "wrong" malloc and then passed to tcmalloc's free. Which, again, should not be possible at all, given how linking works.

Also could this be actual app-side (or some library you use) bug? Does that happen really early your program's life or later? (later would be evidence that it is actually some memory corruption that led to attempt to free bogus pointer)

**Comment by alvaropalmaaste** [comment]
OK, let me generate a small sample and I'll come back to you. Thanks for the quick response.
