### ISSUE TITLE
Why e2k support is removed?

### ISSUE THREAD

**Issue by ColumbusUtrigas** [gperftools/gperftools#1345]
There is a commit 9d44463380716ebad2f8ba13ce8a737f22bb2602 which reverts the old commit with addition of e2k arch support.

Pull request where it was presented:
https://github.com/gperftools/gperftools/pull/1243

![image](https://user-images.githubusercontent.com/26329456/175075350-97916f0c-3d96-4ed3-9c25-8569f215bde2.png)

Why?

**Comment by qfox** [comment]
Don't ask. Revert again!

**Comment by ColumbusUtrigas** [comment]
I mean, it could be done by design, maybe a few lines of code with e2k support really break something crucial. This issue exists to find out the purpose of the revert. I think the best way would be to mention @alk directly.

**Comment by alk** [comment]
No way to test. Plus personal position. This hardware is used mostly by evil organizations (government etc) in evil country. Sorry if it offends you or something. Cannot do otherwise.

**Comment by AsGreyWolf** [comment]
It's just unethical. In Russia we call it "the watchman syndrome".

**Comment by a1batross** [comment]
@alk

E2K is more oriented towards private organizations, when their sparc machines are made specifically for military. It's (kinda?) a lesser evil than you think. Anyone can get free access to Elbrus machine, through http://elbrus.6te.net/.

IMHO, it's kinda weird to talk who is evil or not, while working at Google.

**Comment by makise-homura** [comment]
> No way to test.
As @a1batross said above, there _is_ a way to test--just request the access through http://elbrus.6te.net/, also you may ask for support and discuss things you found out in https://t.me/elbrus_gensokyo .

**Comment by fwflunky** [comment]
youre all support nazism?

**Comment by alk** [comment]
https://groups.google.com/g/gperftools/c/U5PoNJ9rKaY with some more update.

**Comment by makise-homura** [comment]
> https://groups.google.com/g/gperftools/c/U5PoNJ9rKaY with some more update.

Keeping in mind the fact there's no doubt that it's your decision what to do with your own repository, still I think you've targeted the wrong people. As you said, there is no problem to keep this patch in distro's package sources repository (be it MCST Elbrus Linux aka OS Elbrus, Alt Linux, or Astra Linux Leningrad), so these, like, "evil" organizations, who use certified distros and have no right to install or update software, will just continue to use distro version of gperftools and won't suffer from it. But enthusiasts who want to experiment with the latest upstream, will either be unable to build straight-out-of-the-box if they don't know about the patch, or need to maintain theirs own fork with this patch. So you did no impact on "evil guys", but made FOSS enthusiasts' life much harder.

About GPL, MCST still continues to say "there are problems in finding consent with initial customer, but we're working about it"; still Elbrus Linux build system and source code are sold as a separate project. Actually there should be no problem if someone decides to spend their own money to officially order an Elbrus machine, ask for source code (maybe pay for it, if it is considered a "media cost", despite clearly not being it), and then distribute GPL parts of distro freely. But still there was no one, and organizations are tending to take additional consents like "formally we have a right to distribute, but we promise not to" from MCST, so it's not a way either. And looking at that hysteria like "we won't obey international laws because who will punish us for disobedience?" in Russian lawmaking since the war has started, I'm afraid time may be lost already.

P.S. That "remove x86" stuff I've seen some days before was really looking like a nice illustration of what it will result in, if one would be truly consistent rather than demonstrative on "removing evil architectures".

**Comment by alk** [comment]
I'll elaborate some more. What I write below is of course IMHO and personal. And doesn't change my intention to remain civil and neutral in my role as maintainer. This ticket's discussion is of course a notable exception to neutrality. But the requirement of having civil discussion is of course universal. Un-civil comments will lead to bans.

My behavior is rational. It is not about consistency with some generic pacifism. It is consistent with sanctions and free world intention to ruin the aggressor's military might. Which is itself a rational outcome of what happened.

Common CPUs like arms, x86 etc are civil products. Civil products are occasionally used to build weapons. e2k is different. It wouldn't exist without the military. With all the secrecy and NDAs we can see clearly what kind of organization curates this project. Those NDAs imply clearly that their opinion is that CPU has a military/"national security" role. The role of hardware and software on the battlefield will only increase. With sanctions blocking some of the most common CPU options for aggressor's military, it is inevitable that elbrus will eventually be used for weaponry (if not already). Moreover we can easily predict that the military will get priority when getting whatever limited supply of chips that will be available. I.e. whatever civil/academia organizations will get, will be leftover from military use. So that makes elbrus mostly-military cpu. (Sure, none of its architecture is inherently military; but it's role in practice is)

So IMO free software enthusiasts that work specifically on improving software support for this cpu architecture are directly contributing to aggressor's military might. That makes us enemies. Saying this without any hatred or drama. Hoping some of you will eventually realize what you're doing.

**Comment by ColumbusUtrigas** [comment]
Well, that has a place to be, actually.

I'm not sure if this revert really making any damage to the opposing country, and I definitely cannot agree with these actions, because if you are supporting/harming any of the conflicting sides, you are actually becoming some sort of a soldier in the conflict. And in my opinion, the best tactic would be not to support nor harm any of the sides, because it can quickly dehumanize your opponent in your eyes and demonize you in the opponent's eyes, which is good soil for continuing the conflict forever. Thus, cannot agree with the rationality of these actions.

The project, I think, is already forked in e2k project, so the maintaining subj architecture will be on someone else's soul. At least, this is how I understand you. Just hope you ain't "reverting" anything IRL to your colleagues and other people in general. (not trying to bully or joke at you).

It is a more philosophical question though. Concluding everything, in your words, I think general pacifism is more productive. "Overcome evil with good" IMO does make sense.
Thanks for editing your first response in a less offensive manner.

I think it is a good idea to stop this discussion because it looks like it is not going anywhere. And I have a feeling that there will be more undesired toxicity, probably from both bubbles.

I personally just can be glad that parts of my family and some friends living dangerously close to the "place of action" on both sides of the border are alive and mostly OK.

Message to anybody, probably in the future:
Don't be brainwashed, stay human.

Thanks.
