### ISSUE TITLE
Exception in tc_malloc during allocation

### ISSUE THREAD

**Issue by dawld** [gperftools/gperftools#1352]
Hi,
I have flaky but reproducible case where an exception is launched in the libtcmalloc_minimal.dll. For the context: We have a C# application which is tested by C# test suite. The C# application consists of a CLI wrapper around an C++ libary which is using tc_malloc to allocate memory. Due to the flakyness I expect the Garbage collection of C# to be at work. I would understand in exception in the deallocate coming from a double delete or other problem with ownership. Here the exception is launched during an allocation... 
The callstack :

![image](https://user-images.githubusercontent.com/108868149/177788161-e0b62f90-643b-46b7-9d50-f7d642d3450c.png)

If you could give me a hint what happens here and where could be the problem I would be happy!
Thanks in advance,
David

**Comment by dawld** [comment]
Hi,
When I use the standart malloc instead of tc_malloc everything works fine. Since the libarys are dynamically loaded can it be that some parts are allocated using malloc and deallocated with tc_malloc or vice versa? How can I check if my setup is correct ?

**Comment by alk** [comment]
Some sort of sanitizer/bounds checker/whatever is available. That "stock" memory allocator doesn't crash, unfortunately doesn't prove anything. (There is also similar subset of cases where stock malloc would crash but tcmalloc wouldn't. Because not all kinds of misuses/bugs lead to crashes for various reasons)
