### ISSUE TITLE
Average time per call/Number of times function was called?

### ISSUE THREAD

**Issue by DUOLabs333** [gperftools/gperftools#1480]
With the CPU profiler, I can get a rough estimate of how much time was spent in each function. However, this is often not enough to tell me which functions are the slowest --- functions that are called more will naturally take more total time. So, is there a way to get the times a function was called in order to normalize the numbers?

**Comment by alk** [comment]
Indeed, sometimes functions are hot because they're called too often. And sometimes they're hot because they can be made run faster.

No, sampling profilers cannot give you this information directly. But indirectly it might be possible to infer this comparing hotness of instructions (although this could be unreliable even with "no skid" perf profiles), or comparing hotness of functions on the same "path".
