### ISSUE TITLE
TCMalloc built with mingw-w64 deadlocks during startup when pthread-based TLS is enabled

### ISSUE THREAD

**Issue by lennoxho** [gperftools/gperftools#1483]
Here's the call stack
![tcmalloc mingw pthread deadlock no tls](https://github.com/gperftools/gperftools/assets/9140100/deba1232-9e08-4585-9f79-c88217a90614)

The `??`s from `libwinpthread-1.dll` are calls to `pthread_setspecific()`.
Here's the line we are stuck on (it's a spinlock) https://github.com/mingw-w64/mingw-w64/blob/86a5e0f41683d8e60b3756712e7a417055d291dc/mingw-w64-libraries/winpthreads/src/thread.c#L913

The spinlock implementation in question
https://github.com/mingw-w64/mingw-w64/blob/86a5e0f41683d8e60b3756712e7a417055d291dc/mingw-w64-libraries/winpthreads/src/spinlock.c#L50

Looks like the MinGW port of `pthread_setspecific()` is not reentrant.

Identified with this flavour of MinGW
https://github.com/brechtsanders/winlibs_mingw/releases/tag/13.2.0posix-17.0.5-11.0.1-ucrt-r3

The build flag in question is `HAVE_PTHREAD`.
I'm currently working on a changelist to disable it by default in the CMake build

**Comment by lennoxho** [comment]
https://github.com/gperftools/gperftools/pull/1485

**Comment by alk** [comment]
First of all, thanks a lot for looking at this and reporting the issue.

So I am able to reproduce the deadlock and indeed the issue is they're calling realloc while holding their internal lock.

Deadlock is only reproducible on "posix" variant of mingw that debian ships with mingw cross compiler, not their default "win32" variant. (And this is all mega-stale msvcrt, sadly no ucrt option there yet)

Here is what I think we should be doing:

a) general philosophy is now to embrace threading rather than trying to avoid it. So all this "don't include pthreads" logic should go. It only adds complications and multiples configurations that require additional testing. (It made sense for us in past, but not anymore; see #1110 for some more background).

b) since mingw-pthreads config has "incompatible" pthreads implementation we should try using windows native API (make it same for MSVC compiler&runtime as well). I.e. we only use threading API for pthread_atfork (doesn't apply to windows & mingw), and for per-thread storage (including deallocation when thread dies). The code currently builds all that around pthreads, "simulating" it on win32. Perhaps we should consider generalizing this. I'd like us to consider native C++ API, but that same mingw+posix config is likely to be borked there. Worth checking what competition does (jemalloc likely does pthreads, mimalloc being more windows centric and newer might have interesting ideas in this area)

c) NOMINMAX stuff should be fixed separately (with or without config.h matter consolidation; likely without)

If you have time to work on this let me know. If not, I'll eventually find time to do it myself. We cannot afford doing adventurous unique ptr hacks like you suggest in pull request.

**Comment by lennoxho** [comment]
Give me a few days to put something together.

I think we can split the work discussed here into a couple of PRs
1. Consolidate MSVC & MinGW TLS/threading implementations around WinAPI.
  - I expect this to be more of a cleanup/refactoring task, probably no new code needs to be introduced
  - This should already unblock Autotools-MinGW builds, and will fix this issue #1483

2. Fix CMake MinGW & MSVC builds
  - Also ensure implicit TLS is disabled for #1484
  - Also ensure `config.h` isolation between CMake & Autotools/VSProj to avoid configuration conflicts as described in #1482

With both of those PRs, #1485 will be resolved.

**Comment by lennoxho** [comment]
#1487

**Comment by lennoxho** [comment]
Resolved with #1487 by moving MinGW builds to always use WinAPI TLS
