### ISSUE TITLE
cpu profiler generates multiple output files

### ISSUE THREAD

**Issue by iambingoNJU** [gperftools/gperftools#1493]
When I run my program with `LD_PRELOAD=.../lib/libprofiler.so CPUPROFILE=a.prof ./a.out`, it generates multiple output files, in the form of `a.prof_93351`. I think I should only get a single output file named `a.prof` from the doc. So what does this `_93351` suffix mean? It seems it has some relationship with pid. And some output files have size of 0.

![image](https://github.com/gperftools/gperftools/assets/15451671/0ca448b4-b9c5-49bd-991b-ca845bc31baa)

**Comment by alk** [comment]
This happens if/when your program forks another process-es. Note, that since you're LD_PRELOADING and enabling CPU profiling via environment variable, you end up with everything that your shell command spawns being "profiled".

And then we have a logic that "main" process gets no-suffix file, and rest are getting suffix appended. You can check what the command was by looking at the end of those pprof files. We have /proc/<pid>/maps appended there which includes program name.
