### ISSUE TITLE
Interpreting pdf call graphs

### ISSUE THREAD

**Issue by adamweis-qcom** [gperftools/gperftools#1504]
I'm attempting to use gperftools to profile the heap usage of a large proprietary project and am having a little trouble understanding the output showing a callgraph in pdf form.

Namely I don't understand how a graph node can be using more memory than the sum of its callees. We have examples where this appears to be the case.

**Comment by alk** [comment]
This condition "total > sum of childs" likely means that your node also allocates. Or somehow wrongly considered to be allocating, perhaps due to backtracing glitches. See https://github.com/gperftools/gperftools/wiki/gperftools'-stacktrace-capturing-methods-and-their-issues

To confirm, take pprof from github.com/google/pprof and use -raw option to see actual samples.
