### ISSUE TITLE
Tcmalloc not obeying max thread cache limit

### ISSUE THREAD

**Issue by coder-saab001** [gperftools/gperftools#1511]
I tried setting a limit on total thread cache bytes as it was going beyond the memory budget we have for our application given that we have a few hundred long-lived threads using. 
```
MallocExtension::instance()->SetNumericProperty(
      "tcmalloc.max_total_thread_cache_bytes",
      FLAGS_tcmalloc_max_total_thread_cache_bytes);
```
But it does not obey the imposed limit. When I tried digging a bit into the code, I found that even we are setting the overall thread cache to the given value here https://github.com/gperftools/gperftools/blob/master/src/thread_cache.cc#L384 (min bound of which is kMinThreadCacheSize [ = 512 kB]) but later inside the function RecomputePerThreadCacheSize() https://github.com/gperftools/gperftools/blob/master/src/thread_cache.cc#L356 we are again setting per_thread_cache_size_ to a lower bound of 512 kB. Say we have 100 threads in the application, which means we have (512kB * 100 = ) 50MB of overall thread cache. Isn't that huge?

This means that setting the overall thread cache size is of no use unless we configure it greater than `kMinThreadCacheSize * no of threads`.

Is this what is expected? Isn't it a bug?
Ideally, shouldn't we have two variables `kMinThreadCacheSize` and `kMinPerThreadCacheSize` where `kMinPerThreadCacheSize` is set to some lower value than 512kB?

cc: @alk

**Comment by alk** [comment]
Indeed, that is the logic in the cods. We don't have to maintain it exactly as it is. But any changes need to be very carefully evaluated. Test coverage added as well, although this area is indeed difficult to comprehensively cover with tests.

My take is in principle 50 megs for modern program with ~100 threads seems like a small overhead. Typical programs eat a lot more than that (but, sure, not always; I am not saying we're perfect).

I welcome you to consider proposing updated behavior.

But also do consider checking MallocExtension::MarkThreadIdle API as if you have many threads, there is chance many/most will be truly idle. In fact Google's internal code had (maybe still does have) a logic that if a thread is sleeping on abseil Mutex (or maybe more general primitive, don't recall) for longer than certain amount of time (don't recall how much, but likely hundreds of millis or more) then it wakes up and calls MarkThreadIdle. Indeed, I see what appears to be some evidence of this (long obsolete) logic in PerThreadSem::Tick in abseil.

**Comment by coder-saab001** [comment]
I agree with whatever you said. But 500kB for a single thread is still on the higher side.
How about making this configurable via some env? This way we need not be much worried about testing and all.

https://github.com/gperftools/gperftools/pull/1513

**Comment by alk** [comment]
Thanks for the proposal, but we'll need more evidence here. Have you actually tried to apply this setting? Which value(s)? Have you actually observed whatever end result (total memory usage) improved?

And, no, sadly, "configurable by environment variable" doesn't imply we don't need be worried about testing. What happens if in some next version I or someone else silently breaks this knob you're adding.

**Comment by coder-saab001** [comment]
Yes, in my application with approx. 90 threads, thread cache freelist graph with setting
```
MallocExtension::instance()->SetNumericProperty(
      "tcmalloc.max_total_thread_cache_bytes", 0);
```
which essentially lower bound per thread cache to 512kB
is 
(Y-axis show thread-cache-freelist in MBs with time)
<img width="1429" alt="image" src="https://github.com/gperftools/gperftools/assets/76659019/1891b1b6-15d2-44d8-8f1a-32700ad2abc5">

Its about 20MB and still increasing

After setting env to 32k (per thread cache) as given in above PR, 

`export TCMALLOC_FORCE_LOWER_BOUND_PER_THREAD_CACHE_BYTES=32768`

graph is,

<img width="1024" alt="image" src="https://github.com/gperftools/gperftools/assets/76659019/1b92e26f-db1b-47e3-b2e1-05483bb3a666">

Thread cache is capped to 32kB * 90 threads ~ 2.8 MB

Anything you can suggest for testing...

**Comment by alk** [comment]
Thanks for the comprehensive update. So testing this could be simply making sure you're able to set lower limit, run N threads, see that total thread cache size is indeed bounded. I advise adding it to tcmalloc_unittest.cc (but don't bother trying to re-use whatever abstractions we use there for threading; just use c++ standard threads directly). I also recommend you consider either adding or even changing this configuration parameter from environment variable to one of the supported settings MallocExtension::SetNumericProperty. It'll make testing easier too.

For the change itself. It is good that you're able to see lower memory usage. Another question is are you still seeing whatever benefits you expect from using gperftools (as opposed to, say, simply trusting glibc's malloc which is decent). So I am not sure if you're able to describe your use case some more, but I do advise you (perhaps somewhat against my interested of spreading usage of gperftools) to consider what it is you're trying to achieve here.

Asking because gperftools is quite great at a certain conditions. We're not best at lowering fragmentation, but we're okay (and better that some). And we're particularly good (not far from best) at fast-path malloc performance. But in order to see that benefit we pretty much require large enough caches. Because when central freelist or page heap gets involved, we're (unlike most competition) non-sharded. So we don't scale locking-wise very well in those cases. And your tweaking is pretty much about moving your workloads into this slower and less scaleable state. So then I do encourage you to think (and measure when possible) what it is you're trying to achieve.

And btw, there are likely other, perhaps, less riskier means to reduce total thread cache usage while preserving (most of) performance. I.e. one of tweaks that Chromium did to their fork of gperftools is reducing kMaxSize to 32k (which is it's original value in first versions of tcmalloc; bump to 256k was later and specifically to trade off more into "we can use a bit more ram and we can win some more % of cpu savings" territory). Also consider CPP define TCMALLOC_SMALL_BUT_SLOW. It effectively turns off transfer cache, lowering fragmentation at AFAIK nearly negligible performance cost. Chromium did this too.

Anyways, if you wish to continue on this path of doing min thread cache size parameter, I am willing to accept this change provided the code is clean.

**Comment by coder-saab001** [comment]
Hey @alk 
Can you please review https://github.com/gperftools/gperftools/pull/1515

Here I added the support to configure per thread cache without affecting any of the existing workflow.

Please note that tcmalloc also now provides an option to configure **per** cpu cache bytes via MallocExtension::SetMaxPerCpuCacheSize.

**Comment by alk** [comment]
Closing, given that https://github.com/gperftools/gperftools/pull/1515 was merged.
