### ISSUE TITLE
gperftools do not have `SetMaxPerCpuCacheSize()`

### ISSUE THREAD

**Issue by NeilZhy** [gperftools/gperftools#1516]
Why is there a `SetMaxPerCpuCacheSize` interface in the tcmalloc repository, but not in gperftools?

**Comment by alk** [comment]
Because we don't have per-cpu caches. But I guess the real question is why we don't have them. Answer is varied. Main reason is no one has gotten to it yet. But there are also complications that per-cpu caches require rseq support which is only available on Linux and only very recent. Unlike "abseil" tcmalloc, we're trying to offer decent performance and feature set across range of OSes.

Plus per-cpu caches have their own downsides as well. So I am personally not 100% sold on "better-ness" of this approach for all kinds of workloads.
