### ISSUE TITLE
tcmalloc cannot optimize dynamic memory allocation caused by std::vector.

### ISSUE THREAD

**Issue by NeilZhy** [gperftools/gperftools#1517]
I run my application with LD_PRELOAD=tcmalloc . My program uses the third-party library [draco](https://github.com/google/draco) when running.The calling code is similar to the sample in draco.
```
draco::DecoderBuffer buffer;
buffer.Init(data.data(), data.size());

const draco::EncodedGeometryType geom_type =
    draco::GetEncodedGeometryType(&buffer);
if (geom_type == draco::TRIANGULAR_MESH) {
  unique_ptr<draco::Mesh> mesh = draco::DecodeMeshFromBuffer(&buffer);
} else if (geom_type == draco::POINT_CLOUD) {
  unique_ptr<draco::PointCloud> pc = draco::DecodePointCloudFromBuffer(&buffer);
}
```
I captured the dynamic memory allocation flame graph using the bcc tool.Combining perf, objdump, gdb and other tools, we found that a hotspot function with high memory usage is inside draco.The final draco code is as follows:
```
bool DataBuffer::Update(const void *data, int64_t size, int64_t offset) {
  if (data == nullptr) {
    if (size + offset < 0)
      return false;
    // If no data is provided, just resize the buffer.
    data_.resize(size + offset);
  } else {
    if (size < 0)
      return false;
    if (size + offset > static_cast<int64_t>(data_.size()))
      data_.resize(size + offset);
    const uint8_t *const byte_data = static_cast<const uint8_t *>(data);
    std::copy(byte_data, byte_data + size, data_.data() + offset);
  }
  descriptor_.buffer_update_count++;
  return true;
}
```
where data_ is defined as std::vector<uint8_t> data_。
Further analysis shows that every time the application calls the draco code, the entire draco will go through multiple nested calls to new to complete the definition of member variables. Therefore, every time data_ is used, it is a newly defined variable, which can actually be understood as a temporary variable.
My question is, why can't tcmalloc optimize away this part of dynamic memory allocation?
![image](https://github.com/gperftools/gperftools/assets/23352727/dd0c0f2e-e615-46a9-b075-bf5a41cb9308)
cc @alk

**Comment by alk** [comment]
Hi. I am not sure I understand this question well enough. Please clarify what exactly you want to optimize and how. But here is my speculations based and what I see in the fragment of cpu profile above.

So we see time spent in minor page faults (also that droco buffer stuff does memsets and who knows if those are truly necessary, but it looks like biggest contribution is page faults). So if we're talking about long running program and this profile being "steady state" (of which I am not sure and that could be mistake on your part of measuring wrong thing; or not), then we're talking about "too much" memory being cycled through "kernel -> malloc -> kernel -> malloc". I.e. we spent cycles getting memory from kernel (via page faults) then we use this memory, then we free it, then malloc chooses to give it back to kernel. Only to be asked back later. If that is the case (which is quite a bit of assumption on my end; but such workloads do exist for sure), consider tweaking memory release policies in malloc (ours or others). Simplest test is to disable it fully. I.e. tune malloc to never return memory back to kernel.

Alternative possibility is that variable sized-ness of this memory allocation triggers memory fragmentation and malloc is simply forced to go to kernel for more memory, because whatever is has free in page heap doesn't have large enough chunks compared to what is requested. This may be harder to tweak, as usually it could require looking closer as what the code is doing (is really allocating huge chunks of ram? does it have to be all sequential in the ram? etc). Checking this is possible by looking at memory statistics. https://github.com/gperftools/gperftools/blob/de12f89d2a5b88a0ebf88c0700981751afaf90c7/src/gperftools/malloc_extension.h#L113 (There is a bit of heuristic involved, so pass somewhat larger buffer, say 1 meg to get "full" stats)

And as noted above, I cannot rule out that this is simply early stage of whatever your program is doing. So it is loading whatever it needs to load and those page faults are just those initial memory allocations. Speeding those up is possible by tweaking malloc to mass-populate those pages. Kernel (at least Linux) is much faster at mass-populating pages, e.g. via MAP_POPULATE, than page faulting them one by one. Alternative is getting THP working, then allocating 2 megs huge page at once as opposed to in 4k chunks, will be also quite a bit of speed up (but then you may trigger various THP "consolidation" and what-not details in the kernel; so measure and tune).

Anyways, more details are needed to advise. And perhaps even what I wrote above is completely not what you asked.

**Comment by NeilZhy** [comment]
Thank you for your analysis.

What I really want to do is to optimize the problem of dynamic memory allocation, not CPU consumption. The picture above is a hot function for applying for dynamic memory.

I first used the bcc tool funclatency.py to capture __alloc_pages_nodemask in my program (the system physical memory allocation function called by the kernel here).Then use other tools to analyze the results, and the results are shown in the figure below.What I mainly want to optimize is the number of dynamic memory requests every 10s.
![image](https://github.com/gperftools/gperftools/assets/23352727/2c8611e4-473d-4047-87a3-24f3b061c936)

In order to reduce the number of dynamic memory requests every 10 seconds, I used the bcc stackcount tool to capture the call stack when the program called __alloc_pages_nodemask during execution, and obtained the following figure.
![image](https://github.com/gperftools/gperftools/assets/23352727/5783bb81-c531-40c6-9cbc-b14e9516d07e)

From the figure we can see that draco calls a lot of memset. In fact, I used gdb for debugging and found that the memset called here was caused by calling std::vector<uint8_t>::resize() in draco.Also, because std::vector<uint8_t> is dynamically created each time inside draco, each call to resize()/reserve() requires new memory.After I used gperftools/tcmalloc, other dynamic memory allocations were optimized, and only the dynamic memory allocations within draco could not be optimized.

This graph is the statistical result after the program has been running for a long time.

I agree with what you said.
> then we're talking about "too much" memory being cycled through "kernel -> malloc -> kernel -> malloc". I.e. we spent cycles getting memory from kernel (via page faults) then we use this memory, then we free it, then malloc chooses to give it back to kernel.

**Comment by alk** [comment]
Ok then. I misunderstood. So, malloc implementations are just that. They handle memory allocation requests. Avoiding them or not is not our business. Closing.

**Comment by NeilZhy** [comment]
@alk Sorry, I don't quite understand what you mean. I am a tcmalloc beginner. I thought that when using tcmalloc, tcmalloc would help us apply for a piece of memory space in advance, and tcmalloc would hold this memory space and would not release this memory space to the system. So every time I apply for memory, it is equivalent to applying for memory from tcmalloc, not from the system. So my understanding is that after using tcmalloc, the call to __alloc_pages_nodemask can only be captured when the program is initialized, and memory will not be applied to the system during the program running.

**Comment by NeilZhy** [comment]
@alk I used  `MallocExtension* instance = MallocExtension::instance()->SetMemoryReleaseRate(0); ` in my program but it still didn't solve the problem.

**Comment by NeilZhy** [comment]
@alk I also used `MallocExtension::instance()->VerifyAllMemory();` but it still didn't solve the problem.

**Comment by alk** [comment]
Please clarify ***exactly*** what you're trying to achieve here

**Comment by NeilZhy** [comment]
@alk  The flame graph shows that when using draco, exc_page_fault occurs, indicating that the program requested physical memory from the system during runtime. I want to optimize this part.

**Comment by NeilZhy** [comment]
I obtained some content through the `GetStats` interface. How can I analyze it?
[tcmalloc_stats.txt](https://github.com/gperftools/gperftools/files/15410860/tcmalloc_stats.txt)

**Comment by alk** [comment]
Those stats indicate that no memory is being returned to kernel. Also fragmentation is quite low. There is not much more to tune w.r.t. page fault frequency.

And thus I still insist that clarify more. All programs do page faults. What makes you think it requires optimization and why you think malloc can help you there.

**Comment by NeilZhy** [comment]
My idea is that tcmalloc can cache the requested physical memory and not release the memory to the system. Then the program will not request physical memory during running, but request memory from tcmalloc.

**Comment by alk** [comment]
And the stats above are showing us this is exactly what is happening here.

**Comment by NeilZhy** [comment]
However, the results in the call stack flame graph show that memory is still requested from the system.
I added some logs to the memory request location and found that memory is frequently requested here at around 10MB. Will this data have any impact on tcmalloc?

**Comment by alk** [comment]
Look, you're talking above about taking memory from the cache. But before you take anything out, you need to put it there first. In stats you posted above we see that there are about 1.2 gigs of memory your programs take from the kernel. And they are likely the page faults you're observing. All indications are that after that the rate of page fault is largely gone.

**Comment by NeilZhy** [comment]
Thank you for your analysis. The results obtained by tcmalloc::GetStats are not collected during the initialization phase, but are collected during the use process. From the results displayed by Stats, are there always page faults? I don't know how to analyze this Stats result.

**Comment by NeilZhy** [comment]
If tcmalloc::Stats shows that no page faults occurred during the run, but bcc-stackcount can count page faults, I also tried to use other tools, such as perf, and was able to capture page faults during the program run. This is the problem. From the statistics of bcc-stackcount and perf tools, page faults occurred during the program run.

**Comment by alk** [comment]
Hi again. So to clarify, I am not saying absolutely no page faults must happen. I am saying _all programs_ are making page faults. In normal case, vast majority occurs very early, as heap grows to it's stable size (and also as fragmentation climbs to it's stable levels). In RPC services at Google it may occur over couple hours since process start. Although, as noted, vast majority of heap growth happens over first tens of seconds of process' lifetime.

What stats you posted appears to indicate, is that your process looks very normal. We see (at those snapshot moments when you captured stats) that no memory is returned back to kernel. We also see some fragmentation, but the amount relative to total process size looks fairly normal too. This doesn't imply full lack of page faults, but this tells me that page fault rate shouldn't be abnormally high (see scenarios I described above).

In any case, this discussion doesn't seem to go anywhere. If you have concrete proofs that gperftools somehow causes _abnormally_ high rate of page faults. Go ahead and prove it. What you posted so far is there are some page faults, not that this is too high or even high enough to cause significant slowdowns in whatever workload you have.

My advise for you is step back and look again at what you're trying to achieve here. Is page faults really something you need to optimize? If so, when and how those page faults are happening. We have all the code available. You seem to be capable enough. So if we lack any optimizations, I welcome you to propose concrete improvements.

**Comment by NeilZhy** [comment]
Thank you for your analysis and help. In fact, I think the current page fault and dynamic memory allocation frequency are normal and have no impact on the program. After using tcmalloc and optimizing the program myself, it has been reduced from hundreds of thousands of times per 10 seconds to 500 times per 10 seconds. But I still have some difficulties at work in order to achieve certain indicators.
