### ISSUE TITLE
Fast way to determine if a pointer is from tcmalloc.

### ISSUE THREAD

**Issue by kohillyang** [gperftools/gperftools#1527]
Hello gperftools team,

I am currently working on integrating tcmalloc into our win64 program, which depends some closed-source libraries. 

The closed-source libraries in my application sometimes allocate memory using malloc, but they may free that memory directly using RtlFreeHeap. After replacing malloc with tcmalloc, this creates a complication during memory deallocation. I need to determine whether the pointer being freed was allocated by tcmalloc or not. If it wasn't, I have to use the original memory allocator to free it.

To address this, I am currently using a CAS-based hashset to track allocations. This solution works but it imposes a non-trivial performance overhead.

I am wondering if there exists a more efficient solution to this problem,for example, configuring tcmalloc to always allocate memory within a reserved address space range, then I could easily identify tcmalloc-allocated memory without needing a hashset. 

Is there an existing feature in tcmalloc that supports this, or is there another approach you would recommend for my use case? Any guidance or suggestions would be greatly appreciated.

Thank you for your time and assistance.

**Comment by kohillyang** [comment]
MallocExtension::instance()->GetOwnership(ptr) != MallocExtension::kNotOwned can satisfy my requirements.

**Comment by alk** [comment]
If you need fastest-possible, consider also looking e.g. here:  https://github.com/gperftools/gperftools/blob/825b6638cf76aecc5a540d3fa662d157760fc11e/src/windows/patch_functions.cc#L813

I.e. we arrange things so that tcmalloc's fast-path continues to be fast. We assume free gets "our" pointer, look up size class from the address, and then if/when it fails, we get to fallback thingy which in this case ends up msvcrt's free(). So it gives minimal overhead under assumption that most uses will be dealing with our pointers.
