### ISSUE TITLE
does gperftools compitible with https://github.com/google/tcmalloc

### ISSUE THREAD

**Issue by xiedeacc** [gperftools/gperftools#1541]
can link to https://github.com/google/tcmalloc, but use gpertools to CPU and HEAP profiling? why gperftool splited into three project?? gperftools, pprof, and tcmalloc, it's really weird

**Comment by xiedeacc** [comment]
https://google.github.io/tcmalloc/gperftools.html clarified, but can link to https://github.com/google/tcmalloc, but use gperftool to profiling?

**Comment by xiedeacc** [comment]
from https://github.com/google/tcmalloc/issues/248, we can see cannot used for heap profiling, how about cpu profiling?

**Comment by alk** [comment]
They don't offer cpu profiler because google/tcmalloc is just malloc. They amputated some bits off tcmalloc for various reasons, so it mostly just malloc. But not only.  But our libprofiler should be compatible with their tcmalloc.

They actually do offer (much better) alternative to heap profiling. We'll eventually do the same and deprecate and drop our current "heap profiling".

They didn't release heap checker, but it is a dying horse anyways. Use sanitizers.

**Comment by xiedeacc** [comment]
ok, thanks
