### ISSUE TITLE
ReleaseAtLeastNPages sometimes take up 1 second ?

### ISSUE THREAD

**Issue by Rick-Stephen** [gperftools/gperftools#1547]
Hi, tcmalloc seems to have a long interval step within pageheap lock, which causes multiple threads in the process stuck at SpinLock::SlowLock to wait for the pageheap lock.

the problem code is https://github.com/gperftools/gperftools/blob/master/src/page_heap.cc#L204
```
    ReleaseAtLeastNPages(static_cast<Length>(0x7fffffff));
```

Our program is a memory intensive process, and when it executes this code during runtime, causing multiple threads to get stuck and not respond for a long time. Is there a good solution?

We added some trace logs and found that a ReleaseAtLeastNPages call freed 11GB of memory and made 7w system calls madvise. And this take up to 1 second.

Out env:
- linux kernel: 5.10
- arch: aarch64
- gperftools: 2.6.90

The tcmalloc stat like this:
```
MALLOC:    15655906208 (14930.6 MiB) Bytes in use by application
MALLOC: +  19388424192 (18490.2 MiB) Bytes in page heap freelist
MALLOC: +    766933264 (  731.4 MiB) Bytes in central cache freelist
MALLOC: +      9185792 (    8.8 MiB) Bytes in transfer cache freelist
MALLOC: +    109744464 (  104.7 MiB) Bytes in thread cache freelists
MALLOC: +     65929216 (   62.9 MiB) Bytes in malloc metadata
MALLOC:   ------------
MALLOC: =  35996123136 (34328.6 MiB) Actual memory used (physical + swap)
MALLOC: +   1169530880 ( 1115.4 MiB) Bytes released to OS (aka unmapped)
MALLOC:   ------------
MALLOC: =  37165654016 (35443.9 MiB) Virtual address space used
MALLOC:
MALLOC:         272458              Spans in use
MALLOC:            204              Thread heaps in use
MALLOC:           8192              Tcmalloc page size
```

**Comment by alk** [comment]
Thanks for the report.

So what is "7w system calls"? Is that 7 million (1e6) or billion (1e9) or something else ?

In general, yes, this place have potential to cause significant delays. The comment around the line you referenced explains why this is done. Making it much better is a genuine challenge.

There are couple directions of attack I can think of:

a) lean a bit more about those MADV_DONTNEED calls. Does look like your workload might be producing a ton of small chunks and we cannot pass them all in one swoop to kernel. So it takes a ton of syscalls (and syscalls might be quite expensive this days). So perhaps there is something in your workload we could tweak to make it do less page heap fragmentation.

b) depending on workload we might make help it have fewer small spans by configuring tcmalloc with larger logical page size (--with-tcmalloc-pagesize flag of configure)

c) as step 0 you should definitely update to newest gperftools because we've learned how to do those madvise calls without holding "giant" page heap lock. It should help, but whether it'll be enough help remains to be seen.

**Comment by Rick-Stephen** [comment]
Sorry, the words I described before was too localized. "7w system calls" means 70 thousand system calls.

I have some questions about your proposed solution:

a) We understand this and will optimize the program to some extent. However, this scenario is quite extreme and difficult to optimize. Our program may continuously request memory during operation, and then release all memory in a short time when the program is about to exit, which leads to this situation.

b) As mentioned in a), this situation will not occur when the program runs normally, so we do not plan to adjust the tcmalloc-pagesize parameter specifically for this situation.

c) In the latest version 2.15, I see that "ReleaseAtLeastNPages(0x7fffffff)" is still called in function PageHeap::NewLocked within page heap lock. It's just that madvise may be replaced by mmap, but it is still a system call within the lock. Am I wrong?

Finally, I have two questions:

1. If we want to fix this problem quickly, can we directly delete the code near "ReleaseAtLeastNPages(0x7fffffff)"? That is just this [link](https://github.com/gperftools/gperftools/commit/4fd762cead660d4661359ad507083ac4f4967ee4)

2. How is 0x7fffffff in "ReleaseAtLeastNPages(0x7fffffff)" defined? This is a very large number, which will almost certainly release all the free memory of the process. Have you considered the impact of it occupying the pageheap lock for a long time?

**Comment by alk** [comment]
for (a): it is up to you what to do, but here is one "heretical idea": perhaps just exit and don't free anything? Also do keep in mind that this exact code path happens when we are ***allocating*** memory and we couldn't find big enough span of free or released memory. So this should be near peak usage (modulo fragmentation). I.e. if don't do it, we'd 100% surely grab more memory from OS.

for (b): sure

for (c): Ah, I somehow forgot that I haven't haven't returned "unlock-around-release" logic. So please ignore my original comment.

(1). Sure. But please if you ever file more tickets or update existing ones, please, mention that you have made this modification. I.e. you'll re-introduce (arguably rare) issue fixed by original commit that added this logic.

(2). The idea is to release everything.

I am closing this, assuming this is understood. Please reopen if you think some work is needed here or if something isn't yet fully understood.
