### ISSUE TITLE
[QUESTION] per-CPU memory profiling

### ISSUE THREAD

**Issue by HazyMrf** [gperftools/gperftools#1560]
Is there any way to get statistics about per-CPU memory usage using tcmalloc? I mean in C++ code by calling smth like 
```cpp
MallocExtension::instance()->GetStats(...)
```

What I see is just memory usage per whole application, but I want more detailed info about per-CPU memory usage and per-CPU statistics

**Comment by HazyMrf** [comment]
I mean in these docs in tcmalloc official GitHub they support this feature: https://github.com/google/tcmalloc/blob/master/docs/stats.md#per-cpu-information
I checked gperftools `GetStats` internals and I see that a lot of statistics collected by original tcmalloc's `GetStats` is just not present. What's the reason behind such behaviour?

**Comment by HazyMrf** [comment]
I can of course install some custom MallocHooks to save some allocation state inside thread-local variables and so on but I guess there is a way to get per-CPU memory usage without such tricks

**Comment by alk** [comment]
This kinds of (mostly free-form) stats are designed to reflect internal implementation details. They're not necessary good things to use to understand some application behavior details.

We don't have per-cpu stats because we don't per-cpu caches. And if or when we do, it'll be very different than abseil tcmalloc's.

Also please beware of malloc hooks. They ruin performance (at least when it comes to those high rate mostly small allocations that gperftools and abseil tcmalloc are fairly good at).
