### ISSUE TITLE
[tcmalloc] O(n) address-ordered best-fit over PageHeap::large_ becomes major scalability bottleneck on fragmented heap

### ISSUE THREAD

**Issue by alk** [gperftools/gperftools#535]
Originally reported on Google Code with ID 532

```
We run tcmalloc on our very high throughput MySQL master. Join buffers > kMaxPages are
allocated by a large percentage of client threads. Over time, as fragmentation increases,
the large_.returned list grows to contain thousands of Spans, which makes PageHeap::AllocLarge
extremely slow and the pageheap_lock becomes a major source of contention, eventually
slowing down MySQL considerably.

I have written a patch which maintains a doubly linked skiplist to calculate address-ordered
best-fit in amortized O(log(n)) instead of O(n) when the combined size of the large_
normal and returned lists exceed a configurable threshold. We're running it in production
now and according to perf top, the percentage of time spent in PageHeap::AllocLarge
has gone from ~8% overall to ~0.4%.

However, while the time complexity of the skiplist is favorable, its space complexity
(each node is 168 bytes) is obviously substantially less favorable than something like
a red/black tree. I haven't had a chance to do my own measurements yet, but it seems
from everything I've read that allocator metadata size has been shown to have a substantial
impact on CPU cache efficiency, so while this patch may lessen a scalability bottleneck,
it may have negative performance effects. I'm up for implementing a different data
structure for this if that has a better chance of being accepted.

I've also written a small test program that attempts to create a sizeable large_ list,
and then times 100000 allocations and frees from the large list. It's far from perfect,
but it's something.

Patch: https://github.com/jamesgolick/gperftools/compare/master...skiplist-trunk
Test program: https://gist.github.com/jamesgolick/cffa78146af264c191fb
```

Reported by `jamesgolick` on 2013-05-21 23:38:00

**Comment by hendrik42** [comment]
Hi, I'm experiencing performance slowdowns to a standstill, similar to issue 663 or 713, which are marked as duplicates of this ones.

Was there a resolution or workaround to this problem or is it still open?

**Comment by alk** [comment]
No fixes yes. But you can help by describing your use-case more precisely.
There is new page heap implementation in works, so if you describe your
workload it would help us ensure it meets your needs.

On Tue, May 30, 2017 at 12:03 PM, Hendrik Dahlkamp <notifications@github.com

**Comment by alk** [comment]
Hi. Consider testing patch on this branch: https://github.com/alk/gperftools/tree/wip-log-n-page-heap it implements O(log n) manipulation of sets of large spans so should fix scaling issues. It seems to work in my testing.

**Comment by hendrik42** [comment]
Hi Aliaksey,

thanks for the quick responses. I'm running a multi-threaded computer vision program with frequent allocation and deallocation of images. It uses 5-10GB of memory and usually works great, but about 1 in 50 instances slow down to a standstill after running it for 24h. 

Since my last email, I ran it with TCMALLOC_TRANSFER_NUM_OBJ=40 and
TCMALLOC_MAX_TOTAL_THREAD_CACHE_BYTES=2199023255552, as suggested in https://github.com/gperftools/gperftools/issues/713.

This improved it considerably, but I still found occasional slowdowns. I will run your patch and report back if that solves it conclusively.

**Comment by alk** [comment]
Thanks. So with latest code lowering TRANSFER_NUM_OBJ should not be
necessary anymore. Also I'd strongly suggest checking for system-level
issues if the issue is near-full standstill after a while. Particularly
check of swapping-related issues. I.e. by observing rate of major page
faults (and minor too just in case).

If problem still occurs, I would like you to report more details on the
problem. Ideally I'd have output of MallocExtension::instance()->GetStats
and cpu profile from process having this problems.

**Comment by toddlipcon** [comment]
@alk any update on the WIP std::set<> based page-heap implementation you linked above? Curious if you have plans to finish it up. AllocLarge continues to be a concurrency bottleneck for us in long-running server processes.

**Comment by alk** [comment]
There is ongoing effort at google rewriting page heap for hugepages friendliness. So I didn't want to touch page heap. But since that effort is taking a bit longer than we expected, I think it is okay to accept simple fixes for existing page heap. So if you want to pick up and polish this code, I'll happily take such patch (or maybe it already looks perfect and works on your workloads, then just let me know). I was thinking we should switch std set to some intrusive balanced tree implementation (e.g. boost has avl and rb trees). But it is probably okay without.

**Comment by alk** [comment]
I.e. for next couple months I'll be busy with some other work. I cannot spend much time on page heap. But will be happy to review finished work :)

**Comment by toddlipcon** [comment]
Yea, I was also thinking that an intrusive tree (eg from boost) would be great. But I didn't think that a boost dependency in gperftools would be acceptable. It seems like copy-paste importing boost::intrusive::* data structures is also non-trivial. As with most things in boost there is some viral templating going on and we'd need to import half of Boost :)

**Comment by toddlipcon** [comment]
Played a bit with your branch and also compared with implementations based on some other data structures. I used your 'random-mallocer' benchmark as a baseline here. Of course all variants are orders of magnitude better than the O(n) but I was able to also note some differences between various alternatives. Baseline results:
```
 Performance counter stats for './random-mallocer -n 10000':

    13,194,426,376      cycles
        55,064,295      cache-misses

       6.618084836 seconds time elapsed
```

By using a set<pair<Length,Span*>> instead of a set<Span*> we can avoid an extra indirection/cache miss on most comparisons. Since the allocator for the set also allocates from a small set of pages it's likely a lot of the allocations can share TLB entries and avoid TLB misses too. The cost here is an extra 8 bytes per large span, but given that large spans are always at least 1MB I don't think that's of much concern (.0008% overhead).

This speeds up about 10%:

```
 Performance counter stats for './random-mallocer -n 10000':

    11,998,739,572      cycles
        52,524,568      cache-misses

       6.065321629 seconds time elapsed
```
I also tried boost::intrusive::set which gave similar results to the above:

```
 Performance counter stats for './random-mallocer -n 10000':

    11,972,782,765      cycles
        56,905,719      cache-misses

       6.022657601 seconds time elapsed
```
... but of course it involves pulling in boost, which is a bit of a pain. It also expanded the size of the Span struct for the member hook, which wouldn't cooperate with being put inside a union.

A few other things I experimented with with negative results:
- trying to remember the iterator after the removed span and passing it back into std::set::insert as a hint in Carve(). I'm not sure if I implemented it wrong or if it just isn't effective, but it caused a 5-10% slowdown.
- boost::intrusive::splay_set: 20% slower
- boost::intrusive::avl_set: 5-10% slower

All the above were only run with a relatively small number of iterations of the benchmark. Perhaps if you run it longer things get more fragmented and the results could differ. But, seeing as all the solutions are orders of magnitude better than what's in tcmalloc today, and the std::set with the length caching isn't too complex, I think we should move ahead with cleaning up that code and merging it. My hacky code is posted at https://github.com/toddlipcon/gperftools/commit/1bb3db5cfab7ade9f8a86bb5a307340a22335c69 but I can take on cleaning it up and merging with your original patch.

In terms of testing, do you think there are any new specific tests to be added or do the existing system tests cover this enough? I'll try it out on an app or two here just to make sure it doesn't explode.

**Comment by alk** [comment]
This is awesome. Ship it :)

In terms of tests lets make sure new code is covered. I don't think anything beyond that is necessary yet

**Comment by toddlipcon** [comment]
Working on cleaning up the patch... one question about your code:

In PageHeap::ReleaseAtLeastNPages, we previously would pop from the back of the large normal span list. That effectively released the least-recently-used span, since any allocation from a large span would previously prepend the post-carved "leftover" span back to the front. That's a good heuristic because it would likely favor span sizes that weren't useful for allocations and reduce fragmentation over time, right?

In the new code it seems you're using rbegin() in this method. That will always pick the largest NORMAL span to release. I'm afraid of a couple items here:
1) This may exacerbate issues like #754 since, even if we just need to release a few MB, we may choose to release hundreds of MB if there is some large span available. As we saw in the discussion of that issue, madvising large amounts of memory can be quite slow.
2) I would guess that this will result in an accumulation of a larger number of small spans over time rather than tending towards a smaller number of big spans, since we're always releasing the "best" span we have.

Curious whether you agree with the above points, and if so what you think the best approach is:
a) release the smallest span in the large list
b) still pick the largest span, but carve off the appropriate amount if the size of the span is much larger than the requested number of pages-to-release
c) attempt to keep some recency stats of each Span, and then iterate over the first few smallest spans to try to find one which is "not-that-recently-used"

It seems choice 'a' is the simplest (just a matter of removing a single character from your code) but figured I'd get your take rather than try to sneak a small change in that may have larger repercussions.

**Comment by alk** [comment]
Done :) Much thanks. I think new release logic is harmless or possibly improvement.
