### ISSUE TITLE
operator new/delete patching doesn't work on VS2015 making delete-s fail

### ISSUE THREAD

**Issue by alk** [gperftools/gperftools#719]
SUBJ. Looks like change in the way they mangle those symbols.

**Comment by alk** [comment]
Also gperftools currently fail to build under VS2015 due to availability of stdint and inttypes and seemingly also because it now includes them from some headers that we include by default. 
So build fails on our re-redefinitions of int8_t and PRI format specifiers.

**Comment by myrsloik** [comment]
There are a couple of observations to be made:
1. There are no symbols even remotely similar to the mangled new/delete exported in earlier visual studio versions for a trivial new[] and delete[] test program

2. When stepping through instruction by instruction it's obvious that the new/delete operator code ALWAYS gets compiled into a final binary. I tried the normal release/debug/x86/x64 settings and some more but there's no way to get around this (not that you'd really want it).

3. This code appears to always be a simple wrapper for malloc so the other hooking already catches it.

So in the end I don't think there's anything sane you can do to improve it. Or that it's actually necessary.

I can submit a patch that's more clever about present header files when using VS2015 so it compiles without having to edit windows/config.h by default if you want me to.

**Comment by alk** [comment]
Regarding config.h, yes, please. That will save me tons of time.

Regarding 'always a simple wrapper for malloc'. I've installed VS2015 today (to test your patch) and among other stuff found that our unittests actually fail.

Digging a bit deeper I found that it happens as part of STL allocator tests. allocate delegates to operator new which indeed delegates to malloc which is fine. However, at lease somewhere within stl deallocate it calls function that "validates" that pointer which obviously fails since pointer is returned from tcmalloc. And that crashes tests.

**Comment by stephenmax-zhang** [comment]
Any hope for compatible with VS2015?

**Comment by alk** [comment]
Looks like recent fix for #817 actually fixed at least unittests on MSVC2015. Would be great if someone could double-check that.

**Comment by BengtGustafsson** [comment]
I think you are right. I ran into problems after upgrading to VS2015 with the old gperftools 2.4 I was using. Upgrading to 2.5 did not help (_free_base was not patched seemed to be the cause). After upgrading to latest master version it all works fine. Maybe it would be good to make a 2.5.1 release with this fix?

**Comment by volviq** [comment]
@BengtGustafsson I'm trying to build with current master(b0abefd93834d9d9c7ffaae2d23bd48ed8e96477)  with VS2015@SDK10@Windows10 and the build fails with a lot of linker or dependency errors quite early. 
E.g.:
`Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "bool __cdecl tcmalloc::EnterStacktraceScope(void)" (?EnterStacktraceScope@tcmalloc@@YA_NXZ) referenced in function "int __cdecl GetStackFrames(void * *,int *,int,int)" (?GetStackFrames@@YAHPEAPEAXPEAHHH@Z)	low_level_alloc_unittest	C:\Users\sbrandner\devel\win10-sbrandner-jupiter\gperftools\gperftools-src\vsprojects\low_level_alloc_unittest\stacktrace.obj	1	
`

Have you solved those by hand or never come across them? Does the current master/b0abefd93834d9d9c7ffaae2d23bd48ed8e96477 still work fine for you or could you tell me which state of master you used in case it is broken again?

I'm not sure if I should create another bug, because #716 is also still open, and indicates that VS2015 builds are not considered as working yet.

**Comment by alk** [comment]
Looks like missing file. Perhaps I added it as part of my testing

**Comment by BengtGustafsson** [comment]
I just did a zip download and it does not seem possible to reveal the exact version from the zip file contents. The zip file date is 2016-10-10 so I'm sure you can find the version (more or less exactly) if you check history.

**Comment by volviq** [comment]
Thank you. Initially I built by triggering the whole sln build. 
I now tried to manually build everything with "right click-> Build" moving down and up the whole project.
In the end only the following components still show a problem:
* low_level_alloc_unittest
* preamble_patcher_test
* tcmalloc_minimal_unittest_static

At the moment those don't seem relevant for me.

**Comment by pkxpp** [comment]
@volviq it's the same with you.

**Comment by HolyWu** [comment]
Does this issue still exist? Patching mode works fine in VS2017 and unittest passes.

**Comment by alk** [comment]
Debug mode when patching fails. The issue is operator delete/new is generate for each .dll/.exe module built by visual studio and when it is built in debug mode said operator new/delete-s are doing extra checks. Which fails. Feel free to try yourself. tcmalloc_minimal_unittest is enough.
