### ISSUE TITLE
Performance: "spans in use" grows forever

### ISSUE THREAD

**Issue by f18m** [gperftools/gperftools#735]
Hi,

I have 4 server systems employing tcmalloc (version 2.4) that reached about 250/290 hours of uptime. I have been logging some tcmalloc statistics over time. I noticed that even after such long uptime some tcmalloc statistics and in particular the "spans in use" count has never settled on stable values.

The server processing peaks once every day... it has a very repetitive pattern with a period of 1 day so I would expect it to reach stable values pretty soon (after 2-3 days of uptime), but this is not the case.

I'm attaching some plots of tcmalloc stats:
![system1](https://cloud.githubusercontent.com/assets/9748595/10905804/00049490-821d-11e5-9618-4cb5d97c34fc.png)
![system2](https://cloud.githubusercontent.com/assets/9748595/10905802/0000f8c6-821d-11e5-8bb1-d25fc7a73c53.png)
![system3](https://cloud.githubusercontent.com/assets/9748595/10905803/00038e7e-821d-11e5-8ae9-3f939f2402a4.png)
![system4](https://cloud.githubusercontent.com/assets/9748595/10905805/00089090-821d-11e5-9a61-cc57bf000cd7.png)

. **"Spans in use" and "Actual memory used (physical + swap)" seem to grow forever.**

Is this a problem in tcmalloc? Can I do something to reduce the "spans in use" and the actual memory used (e.g., forcing a tcmalloc internal de-fragmentation) ?

Thanks,
Francesco

**Comment by alk** [comment]
Thanks for posting this interesting set of stats. Can you also post output of MallocExtension::GetStats (passing it large buffer) ? That would allow us to see whether those spans are for large segments of memory or not. I would assume it is. 

If so then it is something within app's malloc patterns and tcmalloc's "best match" policy that is causing this.

Also do you happen to allocate/free large chunks often (hundreds of kilobytes)? That could happen with some uses of realloc. If so, then maybe trying to allocate/free them via mmap/munmap directly might help.

I'm also curious about virtual address space size which if I'm right should be huge. It will be output as part of GetStats.

**Comment by alk** [comment]
Also if you're interested in running custom tracing code, I'm can provide
you a patched malloc that has support for tracing of page heap operations.
I'm interested in this data set since it would:

a) help us tune gperftools further

b) help us understand your workload without exposing us to any details of
your app

Let me know if you're interested. If so, I'll work on it this week's
Saturday.

**Comment by f18m** [comment]
Hi Alk,

>Also if you're interested in running custom tracing code, I'm can provide you a patched malloc that has support for tracing of page heap operations.

Thank you very much for your support! I talked with colleagues and we would welcome a custom tracing code, so yes: if you send me a patch, I may run it on our server for some days and then provide you the log files.


>Can you also post output of MallocExtension::GetStats (passing it large buffer) ? That would allow us to see whether those spans are for large segments of memory or not. I would assume it is.

Sure no problem. I have uploaded the .txt files with the full stats retrieved by MallocExtension::GetStats  at
       http://www.filedropper.com/detailed-logs-system1-2-3-4 
the .txt files inside contain an indication of uptime of the server program followed by the output of MallocExtension::GetStats, once every 5min. It's a lot of data actually.
Indeed it may be nice to have a MallocExtension::GetStats() that returns a CSV list of "memory allocation key performance indicators (KPIs)" that would be easier to import in, e.g., Excel for analysis... :)


> Also do you happen to allocate/free large chunks often (hundreds of kilobytes)? That could happen with some uses of realloc. If so, then maybe trying to allocate/free them via mmap/munmap directly might help.

well, honestly the software is pretty large so this is not easy to say. Also allocations depend on the type of traffic the server is processing, so that it's hard to know in advance, but I would expect almost all allocations to be pretty small (less than 10KB more or less). The very-large allocations
that triggered issue #713 are now solved (thanks to your support)... but perhaps something else is lurking somewhere. Maybe I should run the memory profiler on the server program...

Thanks.

**Comment by alk** [comment]
Thanks for posting detailed "timeline" of stats.

So my assumptions ended up quite wrong. Most of those spans are actually short spans and seem to be just normal. As your app grows from ~26 gigs of ram to ~32 gigs it is allocating (and holding) small objects which are backed by small spans. So that is causing "spans in use" to grow. So that seems normal.

I can see how you are concerned with overall heap growth. This is also looks to be within normal, since on your graphs first instance is growing very slowly once it reaches it's normal levels.

Looking at fragmentation on stats that you've posted I see (from end of first .txt file):
* "in use by application": 31917.7 MiB
* "actual memory used": 33852.8 MiB
* which gives:

irb(main):001:0> 1 - (31917.7 / 33852.8)
=> 0.05716218451649502

of memory wasted. Which is ~6 percent which is less than 1/8th (design target). IMHO 6% is good number.

Looks like you are running your server with mlockall or something similar. Which is fine. But it has side effect of disabling "release memory back to OS" feature of malloc. If you disable mlockall, malloc should be able to release those 796.4 megs of memory (Bytes in page heap) to kernel. Which will nearly halve your fragmentation.

**Comment by f18m** [comment]
>I can see how you are concerned with overall heap growth. This is also looks to be within normal, since on your graphs first instance is growing very slowly once it reaches it's normal levels.

However it seems to me that no "normal levels" are reached at all... is this possible? that is, even if slowly, the memory does indeed seem to grow "forever". I have been using (for years) the older tcmalloc v1.8.3 and with that version what I saw was that after 2-3 days the memory usage did settle down (even if to a much higher value than now!).

>Looks like you are running your server with mlockall or something similar. 
yes, indeed this is the case. If I need to continue using mlockall(), do you think that an explicit call to ReleaseFreeMemory() may help defragging? 
I'm not doing it right now because I'm afraid of performance hits for the following next malloc() operations but perhaps doing it e.g., once every 24 hours could help...

**Comment by alk** [comment]
Regarding forever. I don't think it's forever. It might stabilize much later than before, but it should stabilize. I think we should observe if fragmentation ever exceeds reasonable level. 10-12% is still reasonable IMO. And you're only about halfway there. If you do have data that it does eventually exceed this mark, then lets dig into this more.

Regarding ReleaseFreeMemory and mlockall. So ReleaseFreeMemory is using madvise(MADV_DONTNEED, ...) and it simply fails on mlocked region. In order for this to work it has to first explicitly unlock the region before madvise-ing it out. And we don't have that code yet.

I don't know why you're running with mlockall. I can see couple reasons. I believe there are various tradeoffs here and I can see how in some cases running without mlockall is beneficial (slightly smaller memory footprint). I think you should consider trying it out and seeing if it works for you.

**Comment by alk** [comment]
Closing this since I believe it is resolved.
