### ISSUE TITLE
No proc names when profile python extension

### ISSUE THREAD

**Issue by sh1ng** [gperftools/gperftools#752]
I'm profiling xgboost(https://github.com/dmlc/xgboost) with python wrapper.
- OS: Mac OS X el capitan
- gcc-5.2
- yep to profile C/C++ extensions for python https://pypi.python.org/pypi/yep/0.4
- compilation time flags: -Wall -O3 -msse2 -Wno-unknown-pragmas -funroll-loops -g -fno-omit-frame-pointer
- linking time flags: -lprofiler -L/usr/local/Cellar/gperftools/2.4/lib/ -Wl,-no_pie

No function names in any kind of report(sample graph is attached)

Also I've tried to profile xgboost as a console application(binary classification example is available by the link https://github.com/dmlc/xgboost/tree/master/demo/binary_classification). The same result.

Could someone help me?

**Comment by alk** [comment]
I don't know enough about OSX but there is known issue that profiling format does not support unloading dynamically loaded modules. At the end of profiling it is dumping all process mappings and pprof is then used to match addresses in stack traces with offsets in binaries and subsequently to source code lines.

So unloading dynamically loaded objects before that dump happens breaks profiler's assumptions. Try hacking something up so that module is not unloaded. Or consider using profiler's API to stop profiling and dump profile prior to unloading your module.

**Comment by alk** [comment]
See above. Closing as won't fix (nothing we can do I think)
