### ISSUE TITLE
Exception in CentralFreeList::RemoveRange->FetchFromSpans()

### ISSUE THREAD

**Issue by pramod5393** [gperftools/gperftools#760]
Application is link to libtcmalloc.so.4.1.0 on linux machine and compiled with gcc4.7.2

Issue has been observed only once and not reproducible.

Please let me know in case you need to debug this issue further.

```
Program terminated with signal 11, Segmentation fault.
#0  tcmalloc::CentralFreeList::FetchFromSpans (this=0x7f33ab381e60) at src/central_freelist.cc:298
298       span->objects = *(reinterpret_cast<void**>(result));
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.149.el6.x86_64 libgcc-4.4.7-11.el6.x86_64 nss-softokn-freebl-3.14.3-18.el6_6.x86_64
(gdb) bt
#0  tcmalloc::CentralFreeList::FetchFromSpans (this=0x7f33ab381e60) at src/central_freelist.cc:298
#1  0x00007f33ab1632f7 in tcmalloc::CentralFreeList::RemoveRange (this=0x7f33ab381e60, start=0x7f33a88b6af0, end=0x7f33a88b6af8, N=32) at src/central_freelist.cc:269
#2  0x00007f33ab166332 in tcmalloc::ThreadCache::FetchFromCentralCache (this=0x2321d40, cl=Unhandled dwarf expression opcode 0xf3) at src/thread_cache.cc:162
#3  0x00007f33ab16f255 in Allocate (old_ptr=0x9410500, new_size=104) at src/thread_cache.h:341
#4  do_malloc (old_ptr=0x9410500, new_size=104) at src/tcmalloc.cc:1068
#5  do_malloc_or_cpp_alloc (old_ptr=0x9410500, new_size=104) at src/tcmalloc.cc:1005
#6  do_realloc_with_callback (old_ptr=0x9410500, new_size=104) at src/tcmalloc.cc:1205
#7  do_realloc (old_ptr=0x9410500, new_size=104) at src/tcmalloc.cc:1228
#8  tc_realloc (old_ptr=0x9410500, new_size=104) at src/tcmalloc.cc:1526
```

```
0x19a55670:     0x000069fd
(gdb) p *span
$22 = {start = 27133, length = 1, next = 0xaf03980, prev = 0x7f33ab381ea0, objects = 0x6417e500000000, refcount = 67,
  sizeclass = 8, location = 0, sample = 0}
(gdb) p nonempty_
$23 = {start = 0, length = 0, next = 0x19a55670, prev = 0xaef91e0, objects = 0x0, refcount = 0, sizeclass = 0, location = 0,
  sample = 0}
```

**Comment by pramod5393** [comment]
I have used --enable-frame-pointers flag during configuration, and will not be able to provide any test program to reproduce the issue as it is a propitiatory software.

**Comment by alk** [comment]
Hi. It seems inlikely that there is bug in this place of tcmalloc. Since it's code path that is hit pretty often.

I believe it is likely that something in your program has written either past allocated memory or maybe touched freed memory and thus corrupted malloc data structures. I would like to debug this more. I.e. to see if I'm right. But without far details on this issues (like test program) I don't think I can.

Consider building and running your program under address sanitizer and/or valgrind since it will help you finding any issues like that in your program.

Closing bug. But feel free to reopen if you have more data to add.
