### ISSUE TITLE
gperftools don't seem work fine with nginx

### ISSUE THREAD

**Issue by AlaricLiu** [gperftools/gperftools#802]
Hi, Guys.
I have some probloms using gperftools & nginx.

I configured the nginx with command : ./configure --with-debug --with-google_perftools_module --without-http_rewrite_module --without-http_gzip_module --prefix=~/Projects/nginx-1.9.12/bin

Then make nginx and hope the gperftools work fine with nginx.

However, when I run nginx with command: CPUPROFILE=~/Projects/nginx-1.9.12/bin/prof.out sbin/nginx

Nginx showes:
PROFILE: interrupts/evictions/bytes = 0/0/64;

How can I fix this?

**Comment by alk** [comment]
I don't recall what is nginx architecture. Check if it might be forking itself. I.e. child processes might be dumping useful profile that is then overwritten by parent process that is idle.

Also how exactly you're stopping it? I am asking because profile is normally dumped on program's normal exit.

**Comment by alk** [comment]
Gentle ping

**Comment by AlaricLiu** [comment]
Thanks & sorry @alk . 
I then tested nginx with many http requests. Seems like it worked, maybe gperftools need many samples to analyze.
