### ISSUE TITLE
[feature suggestion] There should be an option that actually unmaps the memory.

### ISSUE THREAD

**Issue by yurivict** [gperftools/gperftools#820]
Currently ReleaseFreeMemory() calls madvise. However, this has several problems:
- OS may or may not respect madvise. It is hard to verify and prove that such "released" memory is as good as unallocated. This may vary from OS to OS, and also may depend on some other conditions.
- The process size grows. I have a process that first allocates 8GB, then after a while it frees 8GB and allocates 8.2GB, then it frees 8.2GB and allocates 8.4GB. I observe that the process size grows 8+GB → 16+GB → 24+GB →…→∞. This is, I think, because the previous memory "hole" isn't big enough to fit the subsequent allocated block.
- There are certain industries that run massive memory and CPU intense processes on server farms. They care about memory, observe it, vendors compete on how much memory their products use. The current behavior isn't conducive to gperftools success in such environment.

There should be a function that unmaps the previously mmapped blocks bringing the process size back to where it was.

(I assume TCMALLOC_SKIP_SBRK=Y is used.)

**Comment by alk** [comment]
Can you please elaborate how unmapping versus MADV_DONTNEED helps your case? Also what is wrong with MADV_DONTNEED in those "certain industries". I.e. memory is getting released so what is wrong with that ?

As for your case, if you indeed allocate massive blocks of memory in such massive increments, consider doing mmap manually since this is special enough case that most malloc implementations won't handle. Alternatively, tcmalloc may consider doing mmap/munmap for such massive allocations, similarly to how it is done in glibc malloc. But I don't see how this requires or get helped by tcmalloc supporting munmap instead of madvise.

**Comment by yurivict** [comment]
Process size still shows as growing. Eventually it gets to very high values. There is no easy way in OS to see what is the memory that is not I am not 100% positive that

**Comment by yurivict** [comment]
Process size still shows as growing. Eventually it gets to very high values. There is no easy way in OS to see what is the memory that is not I am not 100% positive that

**Comment by yurivict** [comment]
Actually, on FreeBSD ```MADV_FREE``` is used instead of ```MADV_DONTNEED```.

There are differences between ```munmap``` and ```madvise(MADV_DONTNEED/MADV_FREE)```:
* There is no general and independent way to see how much memory is allocated that hasn't been MADV_DONTNEED-ed.
* When the program runs on the server farm, there are tools that just report the process size/resident size. They generally don't take into account memory that was MADV_DONTNEED-ed. Users will just see the memory size that the process uses. So memory reporting is certainly more straightforward with ```munmap```.
* When touched, MADV_DONTNEED-ed memory will generally re-allocate, the process doesn't get SIGSEGV as it would get when ```munmap``` is done. This leave bugs an opportunity to go undetected. This may happen within tcmalloc library itself, because everything has bugs.
* An advice to use ```mmap``` assumes that C/C++ is used. But there are languages that don't have ```mmap```.
* You are convinced that ```madvise(MADV_DONTNEED)``` makes memory "practically released", but there can be other opinions about this. With MADV_DONTNEED project owner/vendor will have to keep explaining all these points to people. Even I am not convinced.

I agree, ```madvise(MADV_DONTNEED)``` is equivalent to ```munmap``` in many ways and situations, but there are a lot of important differences too.

**Comment by alk** [comment]
Hello again. Thanks for you opinion.

I think tweak to tcmalloc to automagically use mmap/munmap for larger allocations would be quite along the lines of project's direction. I would be happy to take such contribution.

As for munmap, I am not convinced enough to do it myself. And further, if someone proposes patch for munmap support and it is not simple change, I'd strongly weight overhead of complexity versus (very tiny, as far as I can see) benefit of that.

This could probably be done along the lines of general change to abstract more mapping/unmapping operations and move them into SysAllocator.

**Comment by vnikolai** [comment]
Try this, works for me now
https://github.com/gperftools/gperftools/pull/1300

Don't forget to play with ReleaseFreeMemory() / TCMALLOC_RELEASE_RATE / TCMALLOC_AGGRESSIVE_DECOMMIT to see speed up releasing if you need to

**Comment by alk** [comment]
Volodymir's option is really nice, however it does mmap with PROT_NONE which I think in definition of "process size" implied above will still keep size "high". I.e. it  looks like virtual space size was referred to above. I am mentioning this specifically because there are some idea that will take advantage of abundance of virtual address space and actually use plenty of it. While of course keeping control on actually used amounts.

Also I brought this up because MADV_DONTNEED (unlike sadly MADV_FREE) is keeping actually used memory on control. So I wonder if perhaps some of the request was motivated by use of MADV_FREE instead of MADV_DONTNEED (or equivalent).

**Comment by alk** [comment]
I think PROT_NONE is as good as we can get any time soon. Full munmap while theoretically possible will need major work in pagemap facility. Not in near term plans.
