### ISSUE TITLE
Build failure with --enable-minimal on OS X

### ISSUE THREAD

**Issue by terhorst** [gperftools/gperftools#869]
Pretty much what it says. I'm on macOS Sierra. I get the same error on 2.5 and on HEAD.
```
gperftools$ ./autogen.sh 
gperftools$ ./configure --enable-minimal
gperftools$ make

[[ snip ]]

libtool: link: ar cru .libs/libtcmalloc.a
ar: no archive members specified
usage:  ar -d [-TLsv] archive file ...
	ar -m [-TLsv] archive file ...
	ar -m [-abiTLsv] position archive file ...
	ar -p [-TLsv] archive [file ...]
	ar -q [-cTLsv] archive file ...
	ar -r [-cuTLsv] archive file ...
	ar -r [-abciuTLsv] position archive file ...
	ar -t [-TLsv] archive [file ...]
	ar -x [-ouTLsv] archive [file ...]
make: *** [libtcmalloc.la] Error 1
```

**Comment by alk** [comment]
Looks very much like your systems autotools are broken. Can you try building from 2.5 tar.gz instead ? And if it still doesn't work please attach config.log produced by configure on your system.

**Comment by alk** [comment]
I.e. I am referring to this .tar.gz https://github.com/gperftools/gperftools/releases/download/gperftools-2.5/gperftools-2.5.tar.gz which already has configure and Makefile.in-s built using known-to-work autotools.

**Comment by terhorst** [comment]
Same error using that tarball. Some other projects (e.g. (https://github.com/dmlc/xgboost/issues/1007 https://github.com/luaposix/luaposix/issues/46 https://github.com/vcflib/vcflib/issues/85) have also encountered this, my gut feeling is that it's due to a difference in how the OS X archiver behaves in the corner case when there is only one file to archive, as would (?) be the case with ``--enable-minimal``.

[config.log.zip](https://github.com/gperftools/gperftools/files/788469/config.log.zip)

**Comment by alk** [comment]
Interesting. Can you also attach full output of make V=1 and also Makefile-s produced by configure ?

**Comment by terhorst** [comment]
Here you go. 
[Archive.zip](https://github.com/gperftools/gperftools/files/788518/Archive.zip)

**Comment by alk** [comment]
I understand what is going on. Since it is minimal config libtcmalloc.la is actually not supposed to be built anyways. But we build it and link it empty even on GNU/Linux:

$ make libtcmalloc.la
/bin/sh ./libtool  --tag=CXX   --mode=link g++  -g -O2   -o libtcmalloc.la    
libtool: link: ar cru .libs/libtcmalloc.a 
ar: `u' modifier ignored since `D' is the default (see `U')
libtool: link: ranlib .libs/libtcmalloc.a
libtool: link: ( cd ".libs" && rm -f "libtcmalloc.la" && ln -s "../libtcmalloc.la" "libtcmalloc.la" )

That it fails on osex is reasonably fair game. I'll see what I can do. Thanks for reporting it.

**Comment by alk** [comment]
Meanwhile you can workaround by doing touch libtcmalloc.la and continuing with make.

**Comment by terhorst** [comment]
Thanks.

**Comment by alk** [comment]
Uploaded fix. Let me know (and reopen) if it doesn't fix your issue.
