### ISSUE TITLE
MarkThreadTemporarilyIdle behavior may be disruptive to thread cache calculations

### ISSUE THREAD

**Issue by acmorrow** [gperftools/gperftools#880]
This issue is being opened in anticipation of a PR with a proposed fix. However, we are unsure about the correctness or optimality of our proposed fix, and we would like to discuss it with the upstream maintainers. The following is background from one of the MongoDB server engineers describing what we *think* we are observing when we use MarkThreadTemporarilyIdle

> We have an application (mongod) that services incoming requests on a large number of threads. To avoid issues with contention on the central free list we call MarkThreadIdle occasionally before sleeping to wait for a new message in order to return excess memory to the central free list at a time that is unlikely to impact the thread if it is delayed due to contention. This however tears down the entire thread cache data structure so is somewhat expensive; to avoid this we created MarkThreadTemporarilyIdle which returns excess memory to the central free list without tearing down the data structures. However, counterintuitively, we observed that in some cases this actually decreased performance. In those cases we observed that thread cache free memory grew beyond the configured bounds, so we theorized that by returning memory to the central cache free list frequently we were having to then also fetch memory from the central cache free list frequently, fooling the allocator into believing that the thread was perpetually starved of locally cached memory, causing max_length_  to increase, fetching more and more memory from the central free list each time only to have to return it. To avoid this we modified MarkThreadTemporarilyIdle to reset max_length_ (by calling Init()), and this on at least one workload performed better than either calling MarkThreadIdle or calling MarkThreadTemporarilyIdle prior to our change.

CC @markbenvenuto @bdlucas1

**Comment by alk** [comment]
Revisited this. So notably "abseil" version of tcmalloc is just fully destroying thread cache. So they avoid the problem. And yes problem looks real.

We should have a unit test and a fix (and likely do same as "abseil" version to keep things simpler instead of Andrew's more explicit approach).

In addition, in the commit we discussed alternative option of "pooling" hot thread caches instead of dropping objects from freelists (but failing to adjust stats). But this doesn't seem to have any demand, so just mentioning it here.
