### ISSUE TITLE
Missing allocation function: aligned_alloc

### ISSUE THREAD

**Issue by yurivict** [gperftools/gperftools#909]
```aligned_alloc``` can be used along with ``malloc```, yet perftools doesn't have it.

This can cause failure when this pointer is passed to perftools' ```free```.

Specifically, this testcase from OpenAL-Soft project fails with perftools:
> $ LD_PRELOAD=/usr/local/lib/libtcmalloc_minimal.so /usr/local/bin/alloopback
> src/tcmalloc.cc:302] Attempt to free invalid pointer 0x80481c000

**Comment by acmorrow** [comment]
More generally, alignment aware overloads of new are coming in C++17, and GPerftools will need to offer them at some point, as well as the C11 `aligned_alloc` function.

**Comment by yurivict** [comment]
```aligned_alloc``` is needed ASAP, because perftools fails on some projects because of this.

**Comment by alk** [comment]
Can you please elaborate on those failures. Yes, we should have those, but I expect current implementations to impement aligned_alloc by calling to posix_memalign or similar. Isn't this the case in your projects ?

**Comment by yurivict** [comment]
OpenAL project uses ```aligned_alloc``` in some cases. All such allocations go behind peftools' back and its free function later prints "Attempt to free invalid pointer", see my OP.

**Comment by alk** [comment]
Which os is that?

**Comment by yurivict** [comment]
FreeBSD 11.1

**Comment by yurivict** [comment]
OpenAL actually has a configuration variable to use aligned_alloc, "on" by default.

**Comment by alk** [comment]
I think https://github.com/alk/gperftools/tree/wip-aligned-alloc should work. Please test and let us know.

**Comment by llongi** [comment]
Hi, I'm having the same issue, memory allocated with aligned_alloc() crashes at free() time with the above described error. This on Gentoo Linux x86_64, with gperftools-2.6.1.
I applied the commit from the referenced branch and I can confirm everything works fine now! 👍 
I'm somewhat surprised by this because I've been running that code with tcmalloc for a long time now and it worked fine before, also always works fine with default glibc allocator, and at work where I run tcmalloc-2.5 couldn't reproduce the problem either. So maybe something introduced in recent 2.6 series... If you're interested I can try older versions to verify, but this fix works now.

**Comment by alk** [comment]
Yes, please test with older version. I suspect your system's glibc have different implementation of aligned_alloc. Say, it doesn't "delegate" to one of old-style functions (such as posix_memalign). So it should fail with older version as well. I will apply fix shortly.

**Comment by yurivict** [comment]
https://github.com/alk/gperftools/tree/wip-aligned-alloc handles ```aligned_alloc``` fine on FreeBSD.

**Comment by yurivict** [comment]
The fix for the original problem is the latest release.
----
What about C++17's new overloads?

This paper http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0035r4.html lists them.
Should something be done for this in perftools?

**Comment by alk** [comment]
Latest release has support for those as well.
