### ISSUE TITLE
data race in the ThreadCache::SetMaxSize (was: data race in the ThreadCache::SetMaxSize)

### ISSUE THREAD

**Issue by jingel** [gperftools/gperftools#929]
in the function ThreadCache::IncreaseCacheLimitLocked, when one thread call the function  next_memory_steal_->SetMaxSize(next_memory_steal_->max_size_ - kStealAmount);
it operate other thread's member "size_left_", this maybe not thread safety

**Comment by Jianbo-Yang** [comment]
I'm new to tcmalloc, if there's any mistake in what I say below, please point it out...
I think the problem do exist. I checked the code, and size_left_ is not protected, but it is critical region indeed.
size_left_ is accessed in Allocate and Deallocate and other functions. Those functions don't hold pageheap_lock_, and I can't find any functions in the call stack that would hold this lock either. It doesn't make sense to hold lock when call Allocate and Deallocate in threadcache, that's an important reason of high performance.
Besides, when thread cache has to hold a lock to avoid contention or sync, does this lock has to be pageheap_lock_?

**Comment by alk** [comment]
Thanks very much for pointing this out. You're right.

size_left_ is recent optimization that I added on top of change I made to google-internal version. And I clearly missed the fact that we'd be updating it more race-fully. We also don't have much (if any) reviewers like you who are able to spot problems. Google-internal version is different enough (mostly due to per-cpu caches mode) that I don't bother malloc experts from Google.

There was always formally data race setting max_size_, but it was harmless and intentional. max_size_ was mutated under lock and only read racefully. size_left_ we're updating from both locations.

I can undo that optimization tomorrow or so (my current time zone is London). But if you have few minutes yourself and eager to contribute something, please consider fixing it yourself. We just need to revert size_left_ back to size_ I think.

Thanks again for spotting and letting everyone know.

**Comment by acmorrow** [comment]
It has been one of my long term plans to experiment with a per-cpu version of tcmalloc, so it is exciting to hear that it has already been done. Are there plans for that internal google work to be merged into the public facing gperftools?

**Comment by Jianbo-Yang** [comment]
I just got some time and try to fix this bug.
And I have made a [PR#930](https://github.com/gperftools/gperftools/pull/930)
Please review and give comments, thank you

**Comment by jingel** [comment]
@alk I think  revert size_left_ back to size_ is just ok, thanks for your answer.
@Jianbo-Yang  I think your code is ok. compare to older version, your implementation seems miss the "bitwise-or trick" in function ThreadCache::Deallocate, you can compare with older version to see difference. I'm not sure if the trick can take obviously testable change for speed in running time in all cpu platform, but it exist long time, and at least in assembly instruction view, it save the instructions for fast path Deallocate commonly.

**Comment by Jianbo-Yang** [comment]
@jingel thank you for you comments.
You'are right. I miss the bitwise-or trick while reverting size_Left_ to size_. I focused on logic but ignored this optimization.
I have made another commit and the fix is in the [PR#930](https://github.com/gperftools/gperftools/pull/930) now. The build and test passed.
Thanks again

**Comment by alk** [comment]
Merged and making release. Thanks a lot!
