### ISSUE TITLE
cpu profile

### ISSUE THREAD

**Issue by sothy** [gperftools/gperftools#975]
Hi,
My GO application is running inside (one core dedicated to) docker container.
cpu profile is enabled. After the I see outfile.prof. There is nothing inside file.
Why is this behavior?
When I add two dedicated to core containers, outfile.prof has contains.
Thanks for your help

Best regards
sothy

**Comment by alk** [comment]
Go has it's own profiler (but uses upstream pprof). Both are distinct from gperftools. Report your problem elsewhere.

If I'd guess what your problem is, I'd guess that profile isn't accumulated fast enough for profile file to be dumped before you check. If you give it enough time, I'm sure you'll see it. Also make sure your program exits normally. Not sure about Go, but gperftools do dump profile at end.
