### ISSUE TITLE
Why this library has a vc runtime

### ISSUE THREAD

**Issue by libxengine** [gperftools/gperftools#977]
i'm using -mt option compiled.

**Comment by alk** [comment]
Can you please clarify what is exactly your question?

**Comment by obones** [comment]
I believe the OP is asking why the Windows port has a dependency on MSVCRT.dll
This is indeed problematic because that DLL is distributed with the C++ Runtime package which is quite large when the tcmalloc dll itself is less than half a megabyte.
For my own usage, I have changed the project so that it statically links the Microsoft CRT which means that my version of tcmalloc.dll can be deployed pretty much everywhere without any external dependencies.
