### ISSUE TITLE
tcmalloc_debug coredump

### ISSUE THREAD

**Issue by oathupdate** [gperftools/gperftools#997]
I run my process linked with tcmalloc_minimal.a， and it running smoothly
but I run  my process linked with tcmalloc_debug.a, then it coredump.

**Comment by alk** [comment]
Follow advise. It means there is some dangling pointer. There is usually good chance that "normal" malloc won't be affected because you're just overwriting freed data. But occasionally it will be overwriting memory already allocated for new object. Tools like debug malloc or valgrind or asan help you catch those bugs faster.
